<?php
declare(strict_types=1);
require_once __DIR__.'/../public_html/nu-mobile/companion/analytics.php';
$pdo=new PDO('mysql:host=127.0.0.1;port='.(getenv('TEST_DB_PORT')?:'3306').';dbname=nu_mobile_test;charset=utf8mb4','root',getenv('TEST_DB_PASSWORD')?:'test-only-password',[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION,PDO::ATTR_DEFAULT_FETCH_MODE=>PDO::FETCH_ASSOC]);
if($pdo->query('SELECT DATABASE()')->fetchColumn()!=='nu_mobile_test')throw new RuntimeException('Test DB required');
function analyticsOk(bool $value,string $name):void{if(!$value)throw new RuntimeException('FAILED '.$name);echo "PASS $name\n";}
$pdo->exec('DROP TABLE IF EXISTS attempts');$pdo->exec('DROP TABLE IF EXISTS courses');$pdo->exec('DROP TABLE IF EXISTS mock_users');$pdo->exec('DROP TABLE IF EXISTS user_exam_history');
$pdo->exec("CREATE TABLE mock_users(id INT AUTO_INCREMENT PRIMARY KEY,email VARCHAR(191) NOT NULL,name VARCHAR(191) NULL) ENGINE=InnoDB");
$pdo->exec("CREATE TABLE courses(id INT AUTO_INCREMENT PRIMARY KEY,name VARCHAR(20) NOT NULL,title VARCHAR(191) NOT NULL,question_count INT NOT NULL) ENGINE=InnoDB");
$pdo->exec("CREATE TABLE attempts(id INT AUTO_INCREMENT PRIMARY KEY,user_id INT NOT NULL,course_id INT NOT NULL,attempted_questions LONGTEXT NULL,score INT NOT NULL,time_taken INT NOT NULL,attempt_date DATETIME NOT NULL) ENGINE=InnoDB");
$pdo->exec("CREATE TABLE user_exam_history(id INT AUTO_INCREMENT PRIMARY KEY,user_email VARCHAR(191) NOT NULL,course_code VARCHAR(20) NOT NULL,score INT NOT NULL,total_marks INT NOT NULL,difficulty VARCHAR(30) NOT NULL,exam_details LONGTEXT NULL,exam_date DATETIME NOT NULL) ENGINE=InnoDB");
$pdo->exec("INSERT INTO mock_users(id,email,name) VALUES(7,'student@example.com','Student')");
$pdo->exec("INSERT INTO courses(id,name,title,question_count) VALUES(1,'GST101','Use of English',70),(2,'BIO101','General Biology',100)");
$pdo->exec("INSERT INTO attempts(user_id,course_id,score,time_taken,attempt_date) VALUES(7,1,35,2100,'2026-09-01 10:00:00'),(7,1,56,1800,'2026-09-10 10:00:00'),(7,2,90,3600,'2026-09-20 10:00:00')");
$details=json_encode(['questions'=>[['text'=>'Q1'],['text'=>'Q2'],['text'=>'Q3']],'userAnswers'=>[['id'=>'q-0','answer'=>'A','counted'=>true],['id'=>'q-1','answer'=>'','counted'=>true],['id'=>'q-2','answer'=>'C','counted'=>false]]],JSON_UNESCAPED_SLASHES);
$insert=$pdo->prepare('INSERT INTO user_exam_history(user_email,course_code,score,total_marks,difficulty,exam_details,exam_date) VALUES(?,?,?,?,?,?,?)');
$insert->execute(['student@example.com','CHM201',12,20,'easy',$details,'2026-09-04 09:00:00']);
$insert->execute(['student@example.com','CHM201',15,20,'hard',$details,'2026-09-14 09:00:00']);
$insert->execute(['student@example.com','BIO201',18,20,'moderate',$details,'2026-09-24 09:00:00']);
$analytics=new NuPremiumAnalytics($pdo,$pdo);
$missing=$analytics->mock('missing@example.com');
analyticsOk($missing['source_available']===true&&$missing['account_linked']===false&&!$missing['has_data'],'mock account matching is isolated by authenticated email');
$mock=$analytics->mock('student@example.com');
analyticsOk($mock['has_data']===true&&$mock['summary']['attempts']===3&&$mock['summary']['courses']===2,'mock aggregates real attempts');
analyticsOk(abs($mock['summary']['average_percentage']-73.3)<0.1&&$mock['summary']['best_percentage']===90.0,'mock normalises scores by course question count');
analyticsOk($mock['summary']['total_time_seconds']===7500&&abs($mock['summary']['seconds_per_question']-31.3)<0.1,'mock uses recorded timing and pace');
analyticsOk($mock['courses'][0]['course_code']==='GST101'&&$mock['courses'][0]['average_percentage']===65.0,'mock prioritises weakest course first');
$pop=$analytics->pop('student@example.com');
analyticsOk($pop['has_data']===true&&$pop['summary']['attempts']===3&&$pop['summary']['courses']===2,'POP aggregates real history rows');
analyticsOk(abs($pop['summary']['average_percentage']-75.0)<0.1&&$pop['summary']['best_percentage']===90.0,'POP reports score trend from stored marks');
analyticsOk($pop['summary']['answer_coverage_percentage']===50.0,'POP answer coverage ignores non-counted questions');
analyticsOk(count($pop['difficulty'])===3&&$pop['courses'][0]['course_code']==='CHM201','POP exposes difficulty and weakest-course analytics');
$encoded=json_encode([$mock,$pop]);
analyticsOk(!str_contains($encoded,'Q1')&&!str_contains($encoded,'userAnswers')&&!str_contains($encoded,'attempted_questions'),'analytics response never leaks question or answer payloads');
$pdo->exec('DROP TABLE user_exam_history');
$unavailable=$analytics->pop('student@example.com');
analyticsOk($unavailable['source_available']===false&&!$unavailable['has_data'],'missing POP source fails closed without invented data');
$pdo->exec('DROP TABLE attempts');$pdo->exec('DROP TABLE courses');$pdo->exec('DROP TABLE mock_users');
echo "Premium analytics tests passed.\n";
