import 'dart:ui' as ui;
import 'package:flutter/material.dart';
import '../core/skin_theme.dart';
import 'native_ui.dart';
import 'skin_art.dart';

/// Premium skins are complete layout families. Data/actions stay shared while
/// hierarchy, density, geometry, typography and navigation change per family.
class PremiumTopBar extends StatelessWidget implements PreferredSizeWidget {
  const PremiumTopBar({super.key,required this.onTools,required this.onRefresh,required this.onNotifications});
  final VoidCallback onTools,onRefresh,onNotifications;
  @override Size get preferredSize=>const Size.fromHeight(66);
  @override Widget build(BuildContext context){
    final t=SkinTokens.of(context),dark=Theme.of(context).brightness==Brightness.dark;
    final lightShell=<AppSkin>{AppSkin.smartCampus,AppSkin.studentFriendly,AppSkin.minimalAcademic,AppSkin.elegantEditorial,AppSkin.friendlyModern,AppSkin.boldPremium}.contains(t.skin)&&!dark;
    final fg=lightShell?t.ink:Colors.white;
    final bg=lightShell?t.surface.withValues(alpha:.97):Color.lerp(t.background,t.primary,.14)!.withValues(alpha:.97);
    final tech=t.skin==AppSkin.futureTech;
    return AppBar(
      elevation:0,scrolledUnderElevation:0,backgroundColor:bg,foregroundColor:fg,titleSpacing:16,
      title:Row(children:[
        BrandLogo(size:t.skin==AppSkin.minimalAcademic?31:36),const SizedBox(width:10),
        Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,mainAxisSize:MainAxisSize.min,children:[
          Text('NOUN Update',style:Theme.of(context).textTheme.titleLarge?.copyWith(fontFamily:t.displayFont,fontWeight:t.headingWeight,letterSpacing:t.headingTracking,color:fg,height:1.05)),
          const SizedBox(height:3),Text(t.shellTagline,maxLines:1,overflow:TextOverflow.ellipsis,style:Theme.of(context).textTheme.labelSmall?.copyWith(fontFamily:t.bodyFont,fontSize:8.5,letterSpacing:t.labelTracking,color:fg.withValues(alpha:.72))),
        ])),
      ]),
      actions:[
        _TopAction(icon:Icons.search_rounded,fg:fg,tech:tech,onTap:onTools,tooltip:'Search tools'),
        _TopAction(icon:Icons.refresh_rounded,fg:fg,tech:tech,onTap:onRefresh,tooltip:'Refresh'),
        _TopAction(icon:Icons.notifications_none_rounded,fg:fg,tech:tech,onTap:onNotifications,tooltip:'Notifications'),
        const SizedBox(width:5),
      ],
      bottom:t.skin==AppSkin.boldPremium?PreferredSize(preferredSize:const Size.fromHeight(2),child:Container(height:2,decoration:BoxDecoration(gradient:LinearGradient(colors:[t.primary,t.gold,t.primary])))):null,
    );
  }
}
class _TopAction extends StatelessWidget{
  const _TopAction({required this.icon,required this.fg,required this.tech,required this.onTap,required this.tooltip});
  final IconData icon;final Color fg;final bool tech;final VoidCallback onTap;final String tooltip;
  @override Widget build(BuildContext context)=>IconButton(tooltip:tooltip,onPressed:onTap,icon:Container(padding:tech?const EdgeInsets.all(7):EdgeInsets.zero,decoration:tech?BoxDecoration(border:Border.all(color:SkinTokens.of(context).primary.withValues(alpha:.45)),borderRadius:BorderRadius.circular(9)):null,child:Icon(icon,size:20,color:fg)));
}

class PremiumBottomNavigation extends StatelessWidget {
  const PremiumBottomNavigation({super.key,required this.index,required this.onChanged});
  final int index;final ValueChanged<int> onChanged;
  static const _items=<({IconData icon,IconData selected,String label})>[
    (icon:Icons.home_outlined,selected:Icons.home_rounded,label:'Home'),
    (icon:Icons.menu_book_outlined,selected:Icons.menu_book_rounded,label:'Study'),
    (icon:Icons.grid_view_rounded,selected:Icons.grid_view_rounded,label:'Tools'),
    (icon:Icons.newspaper_outlined,selected:Icons.newspaper_rounded,label:'Updates'),
    (icon:Icons.person_outline_rounded,selected:Icons.person_rounded,label:'Profile'),
  ];
  @override Widget build(BuildContext context){
    final t=SkinTokens.of(context),dark=Theme.of(context).brightness==Brightness.dark;
    final tech=t.skin==AppSkin.futureTech,glass=t.skin==AppSkin.glassmorphism;
    final bg=dark?Color.lerp(t.surface,Colors.black,.10)!:t.surface;
    final bar=SafeArea(top:false,child:Container(
      height:68,padding:EdgeInsets.symmetric(horizontal:tech?8:10,vertical:7),
      decoration:BoxDecoration(color:bg.withValues(alpha:glass?.78 ?? 1),border:Border(top:BorderSide(color:(tech?t.primary:t.gold).withValues(alpha:tech?.36 ?? .16)))),
      child:Row(children:[for(var i=0;i<_items.length;i++)Expanded(child:_NavItem(item:_items[i],selected:i==index,onTap:()=>onChanged(i))) ]),
    ));
    if(!glass)return bar;
    return ClipRect(child:BackdropFilter(filter:ui.ImageFilter.blur(sigmaX:12,sigmaY:12),child:bar));
  }
}
class _NavItem extends StatelessWidget{
  const _NavItem({required this.item,required this.selected,required this.onTap});
  final ({IconData icon,IconData selected,String label}) item;final bool selected;final VoidCallback onTap;
  @override Widget build(BuildContext context){
    final t=SkinTokens.of(context),tech=t.skin==AppSkin.futureTech;
    final friendly=t.skin==AppSkin.friendlyModern||t.skin==AppSkin.studentFriendly;
    final active=tech?t.primary:(t.skin==AppSkin.boldPremium?t.gold:t.primary);
    return Semantics(button:true,selected:selected,label:item.label,child:InkWell(borderRadius:BorderRadius.circular(friendly?22:12),onTap:onTap,child:AnimatedContainer(
      duration:const Duration(milliseconds:180),padding:const EdgeInsets.symmetric(vertical:6),
      decoration:BoxDecoration(color:selected?(tech?active.withValues(alpha:.12):Color.lerp(t.surface,active,.12)):Colors.transparent,borderRadius:BorderRadius.circular(friendly?22:12),border:tech&&selected?Border.all(color:active.withValues(alpha:.45)):null),
      child:Column(mainAxisAlignment:MainAxisAlignment.center,children:[
        Icon(selected?item.selected:item.icon,size:selected&&tech?23:21,color:selected?active:t.ink.withValues(alpha:.62)),
        const SizedBox(height:3),Text(item.label,maxLines:1,style:Theme.of(context).textTheme.labelSmall?.copyWith(fontFamily:t.bodyFont,fontSize:9,fontWeight:selected?FontWeight.w800:FontWeight.w600,letterSpacing:tech?.5 ?? 0,color:selected?active:t.ink.withValues(alpha:.72))),
      ]),
    )));
  }
}

class PremiumHomeLayout extends StatelessWidget {
  const PremiumHomeLayout({super.key,required this.greeting,required this.meta,required this.courseCount,required this.walletBalance,required this.setupNeeded,required this.quickServices,required this.birthday,required this.motivation,required this.latestUpdates,required this.onSetup,required this.onCourses,required this.onExam,required this.onStudy,required this.onWallet,required this.onOpen});
  final String greeting,meta,walletBalance;final int courseCount;final bool setupNeeded;
  final List<Map<String,dynamic>> quickServices;final Widget birthday,motivation,latestUpdates;
  final VoidCallback onSetup,onCourses,onExam,onStudy,onWallet;final void Function(Map<String,dynamic>) onOpen;
  @override Widget build(BuildContext context)=>switch(SkinTokens.of(context).skin){
    AppSkin.smartCampus=>_smart(context),AppSkin.premiumDark=>_dark(context),AppSkin.glassmorphism=>_glass(context),AppSkin.studentFriendly=>_student(context),
    AppSkin.minimalAcademic=>_minimal(context),AppSkin.elegantEditorial=>_editorial(context),AppSkin.productivityDashboard=>_productivity(context),AppSkin.friendlyModern=>_friendly(context),
    AppSkin.futureTech=>_tech(context),AppSkin.boldPremium=>_bold(context),_=>_smart(context),
  };
  Widget _list(List<Widget> children)=>ListView(key:const PageStorageKey('home'),padding:const EdgeInsets.fromLTRB(18,18,18,28),children:children);
  Widget _title(BuildContext c,String text,{String? sub}){final t=SkinTokens.of(c);return Padding(padding:const EdgeInsets.only(bottom:13),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(text,style:Theme.of(c).textTheme.headlineSmall?.copyWith(fontFamily:t.displayFont,fontWeight:t.headingWeight,letterSpacing:t.headingTracking,height:t.headingHeight)),if(sub!=null&&sub.isNotEmpty)Padding(padding:const EdgeInsets.only(top:4),child:Text(sub,style:Theme.of(c).textTheme.bodySmall?.copyWith(fontFamily:t.bodyFont,color:t.ink.withValues(alpha:.68))))]));}
  Widget _setup(BuildContext c)=>setupNeeded?Padding(padding:const EdgeInsets.only(bottom:12),child:_rowCard(c,'Complete your student profile','Programme, level, study centre and semester.',Icons.badge_outlined,onSetup)):const SizedBox.shrink();
  Widget _rowCard(BuildContext c,String title,String sub,IconData icon,VoidCallback tap,{Color? tone,bool dark=false}){final t=SkinTokens.of(c),x=tone??t.primary;return Material(color:dark?Color.lerp(t.surface,Colors.black,.17):Color.lerp(t.surface,x,.07),borderRadius:BorderRadius.circular(t.radius),child:InkWell(borderRadius:BorderRadius.circular(t.radius),onTap:tap,child:Padding(padding:const EdgeInsets.all(14),child:Row(children:[Container(width:46,height:46,decoration:BoxDecoration(color:x.withValues(alpha:.14),borderRadius:BorderRadius.circular(13)),child:Icon(icon,color:x)),const SizedBox(width:12),Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(title,style:Theme.of(c).textTheme.titleSmall?.copyWith(fontFamily:t.displayFont,fontWeight:t.titleWeight)),const SizedBox(height:3),Text(sub,maxLines:2,overflow:TextOverflow.ellipsis,style:Theme.of(c).textTheme.bodySmall?.copyWith(fontFamily:t.bodyFont,color:t.ink.withValues(alpha:.68)))])),Icon(Icons.chevron_right_rounded,color:t.ink.withValues(alpha:.48))]))));}
  Widget _metrics(BuildContext c,List<(String,String,IconData,Color)> values){final t=SkinTokens.of(c);return Row(children:[for(var i=0;i<values.length;i++)...[if(i>0)const SizedBox(width:8),Expanded(child:Container(height:94,padding:const EdgeInsets.all(12),decoration:BoxDecoration(color:Color.lerp(t.surface,values[i].$4,.08),borderRadius:BorderRadius.circular(t.radius),border:Border.all(color:values[i].$4.withValues(alpha:.15))),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Icon(values[i].$3,size:20,color:values[i].$4),const Spacer(),Text(values[i].$2,maxLines:1,overflow:TextOverflow.ellipsis,style:Theme.of(c).textTheme.titleSmall?.copyWith(fontFamily:t.numberFont,fontWeight:FontWeight.w800)),Text(values[i].$1,style:Theme.of(c).textTheme.labelSmall?.copyWith(fontFamily:t.bodyFont,color:t.ink.withValues(alpha:.64))) ]))) ]]);}
  Widget _quick(BuildContext c){final t=SkinTokens.of(c),items=quickServices.take(4).toList();return GridView.builder(shrinkWrap:true,physics:const NeverScrollableScrollPhysics(),itemCount:items.length,gridDelegate:SliverGridDelegateWithFixedCrossAxisCount(crossAxisCount:2,crossAxisSpacing:10,mainAxisSpacing:10,mainAxisExtent:t.skin==AppSkin.friendlyModern?132:116),itemBuilder:(_,i){final s=items[i],id='${s['id']}',tone=skinServiceColour(id);return Material(color:Color.lerp(t.surface,tone,.09),borderRadius:BorderRadius.circular(t.radius),child:InkWell(borderRadius:BorderRadius.circular(t.radius),onTap:()=>onOpen(s),child:Padding(padding:const EdgeInsets.all(12),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Icon(serviceIcon(id),color:tone,size:25),const Spacer(),Text(serviceLabel(id,'${s['label']}'),maxLines:2,overflow:TextOverflow.ellipsis,style:Theme.of(c).textTheme.titleSmall?.copyWith(fontFamily:t.displayFont,fontWeight:t.titleWeight))]))));});}
  Widget _commonEnd(BuildContext c,String heading)=>Column(crossAxisAlignment:CrossAxisAlignment.start,children:[const SizedBox(height:18),_title(c,heading),_quick(c),const SizedBox(height:18),_title(c,'Latest updates'),latestUpdates]);
  Widget _smart(BuildContext c)=>_list([_title(c,greeting,sub:meta),birthday,_setup(c),_metrics(c,[('Wallet',walletBalance,Icons.account_balance_wallet_rounded,SkinTokens.of(c).primary),('Courses','$courseCount',Icons.menu_book_rounded,Colors.green)]),const SizedBox(height:12),_rowCard(c,'Next examination','Open your verified personal timetable.',Icons.calendar_month_rounded,onExam,tone:Colors.red),const SizedBox(height:10),_rowCard(c,'Continue studying','Open your courses and choose the next chapter.',Icons.play_circle_fill_rounded,onStudy,tone:Colors.green),_commonEnd(c,'Quick tools')]);
  Widget _dark(BuildContext c){final t=SkinTokens.of(c);return _list([_title(c,greeting,sub:meta),motivation,_setup(c),_rowCard(c,'Next examination','Check your verified personal timetable.',Icons.event_rounded,onExam,tone:t.gold,dark:true),const SizedBox(height:10),_rowCard(c,'Continue studying',courseCount==0?'Add your courses to begin.':'$courseCount courses ready in your library.',Icons.auto_stories_rounded,onStudy,tone:Colors.greenAccent,dark:true),const SizedBox(height:12),_metrics(c,[('Wallet',walletBalance,Icons.wallet_rounded,t.gold),('Courses','$courseCount',Icons.school_rounded,t.primary)]),_commonEnd(c,'Quick actions')]);}
  Widget _glass(BuildContext c){final t=SkinTokens.of(c);Widget glass(Widget child)=>ClipRRect(borderRadius:BorderRadius.circular(28),child:BackdropFilter(filter:ui.ImageFilter.blur(sigmaX:12,sigmaY:12),child:Container(padding:const EdgeInsets.all(15),decoration:BoxDecoration(color:t.surface.withValues(alpha:.58),borderRadius:BorderRadius.circular(28),border:Border.all(color:Colors.white.withValues(alpha:.34))),child:child)));return _list([_title(c,greeting,sub:meta),glass(Column(children:[motivation,_metrics(c,[('Wallet',walletBalance,Icons.wallet_rounded,t.gold),('Courses','$courseCount',Icons.auto_stories_rounded,t.primary)])])),const SizedBox(height:13),_setup(c),glass(Column(children:[_rowCard(c,'Next exam','Open your personalised timetable.',Icons.calendar_month_rounded,onExam,tone:Colors.redAccent),const SizedBox(height:9),_rowCard(c,'Continue studying','Pick up where you left off.',Icons.play_arrow_rounded,onStudy,tone:t.primary)])),_commonEnd(c,'Shortcuts')]);}
  Widget _student(BuildContext c)=>_list([_title(c,greeting,sub:meta),motivation,_setup(c),_rowCard(c,'Important academic notice','Stay ahead of examination and registration updates.',Icons.campaign_rounded,onExam,tone:Colors.red),const SizedBox(height:10),_metrics(c,[('Next exam','Timetable',Icons.calendar_month_rounded,Colors.green),('My wallet',walletBalance,Icons.wallet_rounded,Colors.amber)]),const SizedBox(height:12),_rowCard(c,'Continue studying',courseCount==0?'Add your first course.':'Choose from $courseCount saved courses.',Icons.menu_book_rounded,onStudy,tone:Colors.green),_commonEnd(c,'Quick tools')]);
  Widget _minimal(BuildContext c){final t=SkinTokens.of(c);return _list([_title(c,greeting,sub:meta),_setup(c),Container(padding:const EdgeInsets.symmetric(vertical:14),decoration:BoxDecoration(border:Border(top:BorderSide(color:t.ink.withValues(alpha:.10)),bottom:BorderSide(color:t.ink.withValues(alpha:.10)))),child:_rowCard(c,'Next examination','No guessed dates — open your personalised timetable.',Icons.calendar_today_outlined,onExam,tone:t.primary)),const SizedBox(height:18),_metrics(c,[('Courses','$courseCount',Icons.book_outlined,t.primary),('Wallet',walletBalance,Icons.account_balance_wallet_outlined,t.gold)]),_commonEnd(c,'Quick actions')]);}
  Widget _editorial(BuildContext c){final t=SkinTokens.of(c);return _list([_title(c,greeting,sub:meta),Padding(padding:const EdgeInsets.only(bottom:14),child:Text('“A focused semester is built one deliberate study session at a time.”',style:Theme.of(c).textTheme.titleLarge?.copyWith(fontFamily:'NUReading',fontStyle:FontStyle.italic,height:1.35,color:t.primary))),_setup(c),_rowCard(c,'Next examination','Review your timetable and prepare with intention.',Icons.event_note_rounded,onExam,tone:Colors.red.shade700),const SizedBox(height:10),_rowCard(c,'Continue studying','Return to your reading and revision library.',Icons.auto_stories_rounded,onStudy,tone:t.primary),const SizedBox(height:12),_metrics(c,[('Wallet',walletBalance,Icons.wallet_outlined,t.gold),('Courses','$courseCount',Icons.school_outlined,t.primary)]),_commonEnd(c,'Selected tools')]);}
  Widget _productivity(BuildContext c){final t=SkinTokens.of(c);return _list([_title(c,greeting,sub:meta),_setup(c),Container(padding:const EdgeInsets.all(16),decoration:BoxDecoration(color:t.primary,borderRadius:BorderRadius.circular(12)),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text('NEXT EXAM',style:Theme.of(c).textTheme.labelSmall?.copyWith(color:Colors.white70,letterSpacing:1.2)),const SizedBox(height:6),Text('Open your personalised timetable',style:Theme.of(c).textTheme.titleLarge?.copyWith(color:Colors.white,fontFamily:t.displayFont,fontWeight:FontWeight.w800)),const SizedBox(height:12),FilledButton.tonal(onPressed:onExam,child:const Text('View timetable'))])),const SizedBox(height:12),_metrics(c,[('Tasks','$courseCount courses',Icons.checklist_rounded,Colors.red),('Wallet',walletBalance,Icons.wallet_rounded,Colors.teal),('Study','Resume',Icons.play_arrow_rounded,Colors.blue)]),const SizedBox(height:12),_rowCard(c,'Continue studying','Move one course forward today.',Icons.menu_book_rounded,onStudy,tone:t.primary),_commonEnd(c,'Command shortcuts')]);}
  Widget _friendly(BuildContext c)=>_list([_title(c,greeting,sub:meta),motivation,_setup(c),_rowCard(c,'Upcoming exam','Open your timetable and see what is next.',Icons.calendar_month_rounded,onExam,tone:Colors.green),const SizedBox(height:9),_rowCard(c,'Latest academic notice','Stay ahead of deadlines and important changes.',Icons.notifications_active_rounded,()=>onOpen({'id':'news','label':'News'}),tone:Colors.redAccent),const SizedBox(height:12),_rowCard(c,'Continue studying',courseCount==0?'Start by adding your courses.':'$courseCount courses are ready for you.',Icons.play_circle_rounded,onStudy,tone:Colors.green),_commonEnd(c,'My quick tools')]);
  Widget _tech(BuildContext c){final t=SkinTokens.of(c);return _list([_title(c,greeting,sub:meta),_setup(c),Container(padding:const EdgeInsets.all(14),decoration:BoxDecoration(color:Colors.black.withValues(alpha:.24),borderRadius:BorderRadius.circular(16),border:Border.all(color:t.primary.withValues(alpha:.42)),boxShadow:[BoxShadow(color:t.primary.withValues(alpha:.10),blurRadius:18)]),child:_metrics(c,[('Courses','$courseCount',Icons.school_rounded,t.primary),('Wallet',walletBalance,Icons.wallet_rounded,t.gold)])),const SizedBox(height:11),_rowCard(c,'NEXT EXAM','Open secure personalised timetable data.',Icons.calendar_month_rounded,onExam,tone:Colors.redAccent,dark:true),const SizedBox(height:9),_rowCard(c,'CONTINUE STUDY','Resume your academic workspace.',Icons.play_circle_outline_rounded,onStudy,tone:t.primary,dark:true),_commonEnd(c,'QUICK MODULES')]);}
  Widget _bold(BuildContext c){final t=SkinTokens.of(c);return _list([_title(c,greeting,sub:meta),birthday,_setup(c),Container(padding:const EdgeInsets.all(16),decoration:BoxDecoration(gradient:LinearGradient(colors:[t.primary,Color.lerp(t.primary,t.gold,.34)!]),borderRadius:BorderRadius.circular(16)),child:Row(children:[const Icon(Icons.account_balance_wallet_rounded,color:Colors.white,size:30),const SizedBox(width:12),Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[const Text('WALLET BALANCE',style:TextStyle(color:Colors.white70,fontSize:10,letterSpacing:1.1)),Text(walletBalance,style:Theme.of(c).textTheme.headlineSmall?.copyWith(fontFamily:t.numberFont,fontWeight:FontWeight.w900,color:Colors.white))])),FilledButton(style:FilledButton.styleFrom(backgroundColor:t.gold,foregroundColor:Colors.black87),onPressed:onWallet,child:const Text('OPEN'))])),const SizedBox(height:11),_rowCard(c,'IMPORTANT UPDATE','Review current academic notices and deadlines.',Icons.campaign_rounded,()=>onOpen({'id':'news','label':'News'}),tone:Colors.red),const SizedBox(height:10),_metrics(c,[('Courses','$courseCount',Icons.menu_book_rounded,t.primary),('Next exam','Timetable',Icons.calendar_month_rounded,Colors.red)]),const SizedBox(height:12),_rowCard(c,'CONTINUE STUDYING','Keep your semester moving.',Icons.play_arrow_rounded,onStudy,tone:t.gold),_commonEnd(c,'ESSENTIAL TOOLS')]);}
}

class PremiumStudyLayout extends StatelessWidget {
  const PremiumStudyLayout({super.key,required this.courseCount,required this.services,required this.onCourses,required this.onOpen,required this.onSaved,required this.onDownloads,required this.onFocus});
  final int courseCount;final List<Map<String,dynamic>> services;final VoidCallback onCourses,onSaved,onDownloads,onFocus;final void Function(Map<String,dynamic>) onOpen;
  @override Widget build(BuildContext context){
    final t=SkinTokens.of(context),grid=<AppSkin>{AppSkin.glassmorphism,AppSkin.studentFriendly,AppSkin.elegantEditorial,AppSkin.productivityDashboard,AppSkin.friendlyModern,AppSkin.boldPremium}.contains(t.skin);
    return ListView(key:const PageStorageKey('study'),padding:const EdgeInsets.fromLTRB(18,18,18,28),children:[
      _StudyHeader(courseCount:courseCount,onCourses:onCourses),const SizedBox(height:17),
      if(t.skin==AppSkin.productivityDashboard)...[_StudyMetrics(courseCount:courseCount),const SizedBox(height:18)],
      _SectionTitle('Study resources',subtitle:t.skin==AppSkin.futureTech?'ACADEMIC MODULES':'Everything you need to prepare with confidence.'),const SizedBox(height:10),
      grid?_grid(context):_list(context),const SizedBox(height:20),_SectionTitle(t.skin==AppSkin.elegantEditorial?'Your library':'Study workspace'),const SizedBox(height:10),
      Row(children:[Expanded(child:_mini(context,'Saved',Icons.bookmark_border,onSaved)),const SizedBox(width:8),Expanded(child:_mini(context,'Downloads',Icons.download_outlined,onDownloads)),const SizedBox(width:8),Expanded(child:_mini(context,'Focus',Icons.timer_outlined,onFocus))]),
    ]);
  }
  Widget _list(BuildContext c)=>Column(children:[for(final s in services)Padding(padding:const EdgeInsets.only(bottom:10),child:_resource(c,s,false))]);
  Widget _grid(BuildContext c)=>GridView.builder(shrinkWrap:true,physics:const NeverScrollableScrollPhysics(),itemCount:services.length,gridDelegate:SliverGridDelegateWithFixedCrossAxisCount(crossAxisCount:MediaQuery.textScalerOf(c).scale(14)>18?1:2,crossAxisSpacing:10,mainAxisSpacing:10,mainAxisExtent:150),itemBuilder:(_,i)=>_resource(c,services[i],true));
  Widget _resource(BuildContext c,Map<String,dynamic> s,bool grid){final t=SkinTokens.of(c),id='${s['id']}',tone=skinServiceColour(id),tech=t.skin==AppSkin.futureTech,glass=t.skin==AppSkin.glassmorphism;final fill=tech?Colors.black.withValues(alpha:.22):Color.lerp(t.surface,tone,glass?.12 ?? .08);return Material(color:fill,borderRadius:BorderRadius.circular(t.radius),child:InkWell(borderRadius:BorderRadius.circular(t.radius),onTap:()=>onOpen(s),child:Container(padding:const EdgeInsets.all(14),decoration:BoxDecoration(borderRadius:BorderRadius.circular(t.radius),border:Border.all(color:(tech?t.primary:tone).withValues(alpha:tech?.40 ?? .14))),child:grid?Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Icon(serviceIcon(id),color:tone,size:30),const Spacer(),Text(serviceLabel(id,'${s['label']}'),style:Theme.of(c).textTheme.titleSmall?.copyWith(fontFamily:t.displayFont,fontWeight:t.titleWeight)),const SizedBox(height:4),Text(serviceCaption(id),maxLines:2,overflow:TextOverflow.ellipsis,style:Theme.of(c).textTheme.bodySmall?.copyWith(fontFamily:t.bodyFont,color:t.ink.withValues(alpha:.68))) ]):Row(children:[Container(width:46,height:46,decoration:BoxDecoration(color:tone.withValues(alpha:.12),borderRadius:BorderRadius.circular(13)),child:Icon(serviceIcon(id),color:tone)),const SizedBox(width:13),Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(serviceLabel(id,'${s['label']}'),style:Theme.of(c).textTheme.titleSmall?.copyWith(fontFamily:t.displayFont,fontWeight:t.titleWeight)),const SizedBox(height:4),Text(serviceCaption(id),style:Theme.of(c).textTheme.bodySmall?.copyWith(fontFamily:t.bodyFont,color:t.ink.withValues(alpha:.68)))])),Icon(Icons.chevron_right_rounded,color:t.ink.withValues(alpha:.52))]))));}
  Widget _mini(BuildContext c,String label,IconData icon,VoidCallback tap){final t=SkinTokens.of(c);return Material(color:t.surface,borderRadius:BorderRadius.circular(t.radius),child:InkWell(borderRadius:BorderRadius.circular(t.radius),onTap:tap,child:Padding(padding:const EdgeInsets.symmetric(vertical:14,horizontal:6),child:Column(children:[Icon(icon,color:t.primary),const SizedBox(height:7),Text(label,maxLines:1,style:Theme.of(c).textTheme.labelMedium?.copyWith(fontFamily:t.bodyFont,fontWeight:FontWeight.w700))]))));}
}
class _StudyHeader extends StatelessWidget{
  const _StudyHeader({required this.courseCount,required this.onCourses});final int courseCount;final VoidCallback onCourses;
  @override Widget build(BuildContext c){final t=SkinTokens.of(c),photo=<AppSkin>{AppSkin.glassmorphism,AppSkin.studentFriendly,AppSkin.friendlyModern}.contains(t.skin);return Container(minHeight:photo?190:158,decoration:BoxDecoration(borderRadius:BorderRadius.circular(t.radius),gradient:LinearGradient(colors:[Color.lerp(t.primary,Colors.black,.10)!,Color.lerp(t.primary,t.gold,.25)!])),child:ClipRRect(borderRadius:BorderRadius.circular(t.radius),child:Stack(children:[if(photo)Positioned.fill(child:Opacity(opacity:.38,child:Image.asset(t.heroAsset,fit:BoxFit.cover,alignment:Alignment.centerRight))),Positioned.fill(child:DecoratedBox(decoration:BoxDecoration(gradient:LinearGradient(colors:[t.primary.withValues(alpha:.95),t.primary.withValues(alpha:.46),Colors.transparent])))),Padding(padding:const EdgeInsets.all(18),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text('STUDY',style:Theme.of(c).textTheme.labelSmall?.copyWith(fontFamily:t.bodyFont,color:Colors.white70,letterSpacing:t.labelTracking+1)),const SizedBox(height:8),Text(t.studyHeadline,style:Theme.of(c).textTheme.headlineSmall?.copyWith(fontFamily:t.displayFont,fontWeight:t.headingWeight,letterSpacing:t.headingTracking,height:t.headingHeight,color:Colors.white)),const SizedBox(height:7),Text('$courseCount registered courses · revision tools in one place.',style:Theme.of(c).textTheme.bodySmall?.copyWith(fontFamily:t.bodyFont,color:Colors.white.withValues(alpha:.82))),const SizedBox(height:14),FilledButton.tonal(onPressed:onCourses,child:const Text('My Courses'))]))])));}
}
class _StudyMetrics extends StatelessWidget{const _StudyMetrics({required this.courseCount});final int courseCount;@override Widget build(BuildContext c){final t=SkinTokens.of(c);return Row(children:[for(final item in [('Courses','$courseCount',Icons.menu_book_rounded,Colors.green),('Revision','Ready',Icons.insights_rounded,Colors.blue),('Focus','Start',Icons.timer_rounded,Colors.orange)])Expanded(child:Container(margin:EdgeInsets.only(right:item.$1=='Focus'?0:7),height:92,padding:const EdgeInsets.all(10),decoration:BoxDecoration(color:Color.lerp(t.surface,item.$4,.08),borderRadius:BorderRadius.circular(12)),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Icon(item.$3,color:item.$4,size:20),const Spacer(),Text(item.$2,style:Theme.of(c).textTheme.titleSmall?.copyWith(fontFamily:t.numberFont,fontWeight:FontWeight.w800)),Text(item.$1,style:Theme.of(c).textTheme.labelSmall)]))))]);}}

class PremiumToolsLayout extends StatelessWidget {
  const PremiumToolsLayout({super.key,required this.rows,required this.pinned,required this.onSearch,required this.onOpen,required this.onTogglePin,required this.walletBalance,required this.onWallet});
  final List<Map<String,dynamic>> rows;final Set<String> pinned;final ValueChanged<String> onSearch;final void Function(Map<String,dynamic>) onOpen,onTogglePin;final String walletBalance;final VoidCallback onWallet;
  @override Widget build(BuildContext context){
    final t=SkinTokens.of(context),groups=_grouped();
    return ListView(key:const PageStorageKey('tools'),padding:const EdgeInsets.fromLTRB(18,18,18,30),children:[
      _header(context),const SizedBox(height:14),_search(context),
      if(t.skin==AppSkin.boldPremium)...[const SizedBox(height:14),_wallet(context)],
      if(pinned.isNotEmpty)...[const SizedBox(height:20),const _SectionTitle('Pinned'),const SizedBox(height:10),_render(context,rows.where((s)=>pinned.contains('${s['id']}')).toList(),forceGrid:true)],
      for(final e in groups.entries)...[const SizedBox(height:21),_SectionTitle(e.key),const SizedBox(height:10),_render(context,e.value)],
      if(rows.isEmpty)Padding(padding:const EdgeInsets.only(top:34),child:Center(child:Text('No tools match your search.',style:Theme.of(context).textTheme.bodyLarge))),
    ]);
  }
  Map<String,List<Map<String,dynamic>>> _grouped(){final map=<String,List<Map<String,dynamic>>>{};for(final s in rows){if(pinned.contains('${s['id']}'))continue;final g='${s['group']??'Academic tools'}';(map[g]??=[]).add(s);}return map;}
  Widget _header(BuildContext c){final t=SkinTokens.of(c),upper=t.skin==AppSkin.futureTech||t.skin==AppSkin.boldPremium;return Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(upper?'TOOLS':'Tools',style:Theme.of(c).textTheme.headlineMedium?.copyWith(fontFamily:t.displayFont,fontWeight:t.headingWeight,letterSpacing:t.headingTracking,height:t.headingHeight)),const SizedBox(height:5),Text(t.toolsSubtitle,style:Theme.of(c).textTheme.bodyMedium?.copyWith(fontFamily:t.bodyFont,color:t.ink.withValues(alpha:.68),height:1.35))]);}
  Widget _search(BuildContext c){final t=SkinTokens.of(c),tech=t.skin==AppSkin.futureTech,glass=t.skin==AppSkin.glassmorphism;final alpha=glass?.66 ?? 1;final borderAlpha=tech?.36 ?? .10;final field=TextField(onChanged:onSearch,style:TextStyle(fontFamily:t.bodyFont),decoration:InputDecoration(prefixIcon:Icon(Icons.search_rounded,color:t.primary),hintText:'Find a tool',hintStyle:TextStyle(fontFamily:t.bodyFont),filled:true,fillColor:tech?Colors.black.withValues(alpha:.24):t.surface.withValues(alpha:alpha),border:OutlineInputBorder(borderRadius:BorderRadius.circular(glass?28:t.radius),borderSide:BorderSide(color:(tech?t.primary:t.ink).withValues(alpha:borderAlpha))),enabledBorder:OutlineInputBorder(borderRadius:BorderRadius.circular(glass?28:t.radius),borderSide:BorderSide(color:(tech?t.primary:t.ink).withValues(alpha:borderAlpha)))));if(!glass)return field;return ClipRRect(borderRadius:BorderRadius.circular(28),child:BackdropFilter(filter:ui.ImageFilter.blur(sigmaX:10,sigmaY:10),child:field));}
  Widget _wallet(BuildContext c){final t=SkinTokens.of(c);return Material(color:t.primary,borderRadius:BorderRadius.circular(14),child:InkWell(borderRadius:BorderRadius.circular(14),onTap:onWallet,child:Padding(padding:const EdgeInsets.all(14),child:Row(children:[Container(width:44,height:44,decoration:BoxDecoration(color:t.gold,borderRadius:BorderRadius.circular(12)),child:const Icon(Icons.account_balance_wallet_rounded,color:Colors.black87)),const SizedBox(width:12),Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[const Text('WALLET BALANCE',style:TextStyle(color:Colors.white70,fontSize:9,letterSpacing:1.1)),Text(walletBalance,style:Theme.of(c).textTheme.titleLarge?.copyWith(fontFamily:t.numberFont,fontWeight:FontWeight.w900,color:Colors.white))])),const Icon(Icons.chevron_right,color:Colors.white)]))));}
  Widget _render(BuildContext c,List<Map<String,dynamic>> items,{bool forceGrid=false}){final t=SkinTokens.of(c);final grid=forceGrid||<AppSkin>{AppSkin.studentFriendly,AppSkin.elegantEditorial,AppSkin.productivityDashboard,AppSkin.friendlyModern,AppSkin.boldPremium}.contains(t.skin);if(!grid)return Column(children:[for(final s in items)Padding(padding:const EdgeInsets.only(bottom:10),child:_listTool(c,s))]);return GridView.builder(shrinkWrap:true,physics:const NeverScrollableScrollPhysics(),itemCount:items.length,gridDelegate:SliverGridDelegateWithFixedCrossAxisCount(crossAxisCount:MediaQuery.textScalerOf(c).scale(14)>18?1:2,crossAxisSpacing:10,mainAxisSpacing:10,mainAxisExtent:t.skin==AppSkin.productivityDashboard?132:t.skin==AppSkin.friendlyModern?142:126),itemBuilder:(_,i)=>_gridTool(c,items[i]));}
  Widget _listTool(BuildContext c,Map<String,dynamic> s){final t=SkinTokens.of(c),id='${s['id']}',tone=skinServiceColour(id),glass=t.skin==AppSkin.glassmorphism,tech=t.skin==AppSkin.futureTech,dark=t.skin==AppSkin.premiumDark;final alpha=glass?.60 ?? 1;final borderAlpha=tech?.44 ?? (glass?.35 ?? .13);final iconAlpha=(dark||tech)?.20 ?? .13;final card=Material(color:tech?Colors.black.withValues(alpha:.24):dark?Color.lerp(t.surface,Colors.black,.13):t.surface.withValues(alpha:alpha),borderRadius:BorderRadius.circular(glass?30:t.radius),child:InkWell(borderRadius:BorderRadius.circular(glass?30:t.radius),onTap:()=>onOpen(s),child:Container(padding:const EdgeInsets.all(14),decoration:BoxDecoration(borderRadius:BorderRadius.circular(glass?30:t.radius),border:Border.all(color:(tech?t.primary:glass?Colors.white:tone).withValues(alpha:borderAlpha))),child:Row(children:[Container(width:48,height:48,decoration:BoxDecoration(color:tone.withValues(alpha:iconAlpha),borderRadius:BorderRadius.circular(14)),child:Icon(serviceIcon(id),color:tech&&tone==const Color(0xff17845a)?t.primary:tone)),const SizedBox(width:13),Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(serviceLabel(id,'${s['label']}'),style:Theme.of(c).textTheme.titleSmall?.copyWith(fontFamily:t.displayFont,fontWeight:t.titleWeight)),const SizedBox(height:4),Text(serviceCaption(id),maxLines:2,overflow:TextOverflow.ellipsis,style:Theme.of(c).textTheme.bodySmall?.copyWith(fontFamily:t.bodyFont,color:t.ink.withValues(alpha:.68),height:1.3))])),_pin(c,s)]))));if(!glass)return card;return ClipRRect(borderRadius:BorderRadius.circular(30),child:BackdropFilter(filter:ui.ImageFilter.blur(sigmaX:12,sigmaY:12),child:card));}
  Widget _gridTool(BuildContext c,Map<String,dynamic> s){final t=SkinTokens.of(c),id='${s['id']}',tone=skinServiceColour(id),productivity=t.skin==AppSkin.productivityDashboard,friendly=t.skin==AppSkin.friendlyModern||t.skin==AppSkin.studentFriendly,bold=t.skin==AppSkin.boldPremium;final mix=bold?.13 ?? (friendly?.08 ?? .10);return Material(color:Color.lerp(t.surface,tone,mix),borderRadius:BorderRadius.circular(t.radius),child:InkWell(borderRadius:BorderRadius.circular(t.radius),onTap:()=>onOpen(s),child:Padding(padding:const EdgeInsets.all(13),child:Stack(children:[Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Container(width:40,height:40,decoration:BoxDecoration(color:tone.withValues(alpha:.14),borderRadius:BorderRadius.circular(productivity?10:13)),child:Icon(serviceIcon(id),color:tone,size:23)),const Spacer(),Text(serviceLabel(id,'${s['label']}'),maxLines:2,overflow:TextOverflow.ellipsis,style:Theme.of(c).textTheme.titleSmall?.copyWith(fontFamily:t.displayFont,fontWeight:t.titleWeight,height:1.12)),if(!productivity)...[const SizedBox(height:3),Text(serviceCaption(id),maxLines:1,overflow:TextOverflow.ellipsis,style:Theme.of(c).textTheme.bodySmall?.copyWith(fontFamily:t.bodyFont,fontSize:10,color:t.ink.withValues(alpha:.65)))]]),Positioned(top:-8,right:-8,child:_pin(c,s,small:true))]))));}
  Widget _pin(BuildContext c,Map<String,dynamic> s,{bool small=false}){final id='${s['id']}',on=pinned.contains(id),t=SkinTokens.of(c);return IconButton(visualDensity:small?VisualDensity.compact:VisualDensity.standard,tooltip:on?'Unpin tool':'Pin tool',onPressed:()=>onTogglePin(s),icon:Icon(on?Icons.push_pin_rounded:Icons.push_pin_outlined,size:small?17:20,color:on?t.primary:t.ink.withValues(alpha:.48)));}
}

class _SectionTitle extends StatelessWidget{
  const _SectionTitle(this.title,{this.subtitle});final String title;final String? subtitle;
  @override Widget build(BuildContext c){final t=SkinTokens.of(c);return Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(title,style:Theme.of(c).textTheme.titleLarge?.copyWith(fontFamily:t.displayFont,fontWeight:t.headingWeight,letterSpacing:t.headingTracking)),if(subtitle!=null)Padding(padding:const EdgeInsets.only(top:3),child:Text(subtitle!,style:Theme.of(c).textTheme.bodySmall?.copyWith(fontFamily:t.bodyFont,color:t.ink.withValues(alpha:.62))))]);}
}
