import 'dart:ui' as ui;
import 'package:flutter/material.dart';
import '../core/skin_theme.dart';
import 'native_ui.dart';
import 'skin_art.dart';

/// Premium skins are layout families, not colour presets. These widgets keep
/// data/actions shared while changing hierarchy, density, geometry and chrome.
class PremiumTopBar extends StatelessWidget implements PreferredSizeWidget {
  const PremiumTopBar({super.key,required this.onTools,required this.onRefresh,required this.onNotifications});
  final VoidCallback onTools,onRefresh,onNotifications;
  @override Size get preferredSize=>const Size.fromHeight(66);
  @override Widget build(BuildContext context){
    final t=SkinTokens.of(context),dark=Theme.of(context).brightness==Brightness.dark;
    final lightShell=[AppSkin.smartCampus,AppSkin.studentFriendly,AppSkin.minimalAcademic,AppSkin.elegantEditorial,AppSkin.friendlyModern,AppSkin.boldPremium].contains(t.skin)&&!dark;
    final fg=lightShell?t.ink:Colors.white;
    final bg=lightShell?t.surface.withValues(alpha:.96):Color.lerp(t.background,t.primary,.14)!.withValues(alpha:.97);
    final editorial=t.skin==AppSkin.elegantEditorial;
    final tech=t.skin==AppSkin.futureTech;
    return AppBar(
      elevation:0,scrolledUnderElevation:0,backgroundColor:bg,foregroundColor:fg,
      titleSpacing:16,
      title:Row(children:[
        BrandLogo(size:t.skin==AppSkin.minimalAcademic?31:36),const SizedBox(width:10),
        Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,mainAxisSize:MainAxisSize.min,children:[
          Text('NOUN Update',style:Theme.of(context).textTheme.titleLarge?.copyWith(fontFamily:t.displayFont,fontSize:editorial?19:20,fontWeight:t.headingWeight,letterSpacing:t.headingTracking,color:fg,height:1.05)),
          const SizedBox(height:3),Text(t.shellTagline,style:Theme.of(context).textTheme.labelSmall?.copyWith(fontFamily:t.bodyFont,fontSize:8.5,letterSpacing:t.labelTracking,color:fg.withValues(alpha:.72))),
        ])),
      ]),
      actions:[
        _TopAction(icon:Icons.search_rounded,fg:fg,tech:tech,onTap:onTools,tooltip:'Search tools'),
        _TopAction(icon:Icons.refresh_rounded,fg:fg,tech:tech,onTap:onRefresh,tooltip:'Refresh'),
        _TopAction(icon:Icons.notifications_none_rounded,fg:fg,tech:tech,onTap:onNotifications,tooltip:'Notifications'),
        const SizedBox(width:6),
      ],
      bottom:t.skin==AppSkin.boldPremium?PreferredSize(preferredSize:const Size.fromHeight(2),child:Container(height:2,decoration:BoxDecoration(gradient:LinearGradient(colors:[t.primary,t.gold,t.primary])))):null,
    );
  }
}
class _TopAction extends StatelessWidget{
  const _TopAction({required this.icon,required this.fg,required this.tech,required this.onTap,required this.tooltip});
  final IconData icon;final Color fg;final bool tech;final VoidCallback onTap;final String tooltip;
  @override Widget build(BuildContext context)=>IconButton(tooltip:tooltip,onPressed:onTap,icon:Container(padding:tech?const EdgeInsets.all(7):EdgeInsets.zero,decoration:tech?BoxDecoration(border:Border.all(color:SkinTokens.of(context).primary.withValues(alpha:.45)),borderRadius:BorderRadius.circular(9)):null,child:Icon(icon,size:20,color:fg)));
}

class PremiumBottomNavigation extends StatelessWidget {
  const PremiumBottomNavigation({super.key,required this.index,required this.onChanged});
  final int index;final ValueChanged<int> onChanged;
  static const _items=[
    (Icons.home_outlined,Icons.home_rounded,'Home'),
    (Icons.menu_book_outlined,Icons.menu_book_rounded,'Study'),
    (Icons.grid_view_rounded,Icons.grid_view_rounded,'Tools'),
    (Icons.newspaper_outlined,Icons.newspaper_rounded,'Updates'),
    (Icons.person_outline_rounded,Icons.person_rounded,'Profile'),
  ];
  @override Widget build(BuildContext context){
    final t=SkinTokens.of(context),dark=Theme.of(context).brightness==Brightness.dark;
    final tech=t.skin==AppSkin.futureTech;
    final glass=t.skin==AppSkin.glassmorphism;
    final editorial=t.skin==AppSkin.elegantEditorial;
    final friendly=t.skin==AppSkin.friendlyModern||t.skin==AppSkin.studentFriendly;
    final bg=dark?Color.lerp(t.surface,Colors.black,.10)!:t.surface;
    final bar=SafeArea(top:false,child:Container(
      height:68,padding:EdgeInsets.symmetric(horizontal:tech?8:10,vertical:7),
      decoration:BoxDecoration(color:bg.withValues(alpha:glass?.78:1),border:Border(top:BorderSide(color:(tech?t.primary:t.gold).withValues(alpha:tech?.36:.16)))),
      child:Row(children:[for(var i=0;i<_items.length;i++)Expanded(child:_NavItem(item:_items[i],selected:i==index,onTap:()=>onChanged(i),tech:tech,editorial:editorial,friendly:friendly))]),
    ));
    if(!glass)return bar;
    return ClipRect(child:BackdropFilter(filter:ui.ImageFilter.blur(sigmaX:12,sigmaY:12),child:bar));
  }
}
class _NavItem extends StatelessWidget{
  const _NavItem({required this.item,required this.selected,required this.onTap,required this.tech,required this.editorial,required this.friendly});
  final (IconData,IconData,String) item;final bool selected,tech,editorial,friendly;final VoidCallback onTap;
  @override Widget build(BuildContext context){
    final t=SkinTokens.of(context);
    final active=tech?t.primary:(t.skin==AppSkin.boldPremium?t.gold:t.primary);
    return Semantics(button:true,selected:selected,label:item.$3,child:InkWell(borderRadius:BorderRadius.circular(friendly?22:12),onTap:onTap,child:AnimatedContainer(duration:const Duration(milliseconds:180),padding:const EdgeInsets.symmetric(vertical:6),decoration:BoxDecoration(
      color:selected?(tech?active.withValues(alpha:.12):Color.lerp(t.surface,active,.12)):Colors.transparent,
      borderRadius:BorderRadius.circular(friendly?22:12),
      border:tech&&selected?Border.all(color:active.withValues(alpha:.45)):null,
    ),child:Column(mainAxisAlignment:MainAxisAlignment.center,children:[
      Icon(selected?item.$2:item.$1,size:selected&&tech?23:21,color:selected?active:t.ink.withValues(alpha:.62)),
      const SizedBox(height:3),Text(item.$3,maxLines:1,style:Theme.of(context).textTheme.labelSmall?.copyWith(fontFamily:editorial?'NUReading':t.bodyFont,fontSize:9,fontWeight:selected?FontWeight.w800:FontWeight.w600,letterSpacing:tech?.5:0,color:selected?active:t.ink.withValues(alpha:.72))),
    ]))));
  }
}

class PremiumHomeLayout extends StatelessWidget {
  const PremiumHomeLayout({super.key,required this.greeting,required this.meta,required this.courseCount,required this.walletBalance,required this.setupNeeded,required this.quickServices,required this.birthday,required this.motivation,required this.latestUpdates,required this.onSetup,required this.onCourses,required this.onExam,required this.onStudy,required this.onWallet,required this.onOpen});
  final String greeting,meta,walletBalance;final int courseCount;final bool setupNeeded;
  final List<Map<String,dynamic>> quickServices;final Widget birthday,motivation,latestUpdates;
  final VoidCallback onSetup,onCourses,onExam,onStudy,onWallet;final void Function(Map<String,dynamic>) onOpen;
  @override Widget build(BuildContext context){
    final t=SkinTokens.of(context);
    return switch(t.skin){
      AppSkin.smartCampus=>_smart(context),AppSkin.premiumDark=>_dark(context),AppSkin.glassmorphism=>_glass(context),
      AppSkin.studentFriendly=>_student(context),AppSkin.minimalAcademic=>_minimal(context),AppSkin.elegantEditorial=>_editorial(context),
      AppSkin.productivityDashboard=>_productivity(context),AppSkin.friendlyModern=>_friendly(context),AppSkin.futureTech=>_tech(context),
      AppSkin.boldPremium=>_bold(context),_=>_smart(context),
    };
  }
  Widget _baseList(BuildContext context,List<Widget> children,{EdgeInsets padding=const EdgeInsets.fromLTRB(18,18,18,28)})=>ListView(key:const PageStorageKey('home'),padding:padding,children:children);
  Widget _heading(BuildContext c,String title,{String? sub}){final t=SkinTokens.of(c);return Padding(padding:const EdgeInsets.only(bottom:14),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(title,style:Theme.of(c).textTheme.headlineSmall?.copyWith(fontFamily:t.displayFont,fontWeight:t.headingWeight,letterSpacing:t.headingTracking,height:t.headingHeight)),if(sub!=null&&sub.isNotEmpty)Padding(padding:const EdgeInsets.only(top:5),child:Text(sub,style:Theme.of(c).textTheme.bodySmall?.copyWith(fontFamily:t.bodyFont,color:t.ink.withValues(alpha:.70),height:1.35)))]));}
  Widget _card(BuildContext c,{required String title,required String sub,required IconData icon,required VoidCallback onTap,Color? tone,bool dense=false,bool darkCard=false}){
    final t=SkinTokens.of(c),color=tone??t.primary;
    return Material(color:darkCard?Color.lerp(t.surface,Colors.black,.18):Color.lerp(t.surface,color,.07),borderRadius:BorderRadius.circular(t.radius),child:InkWell(borderRadius:BorderRadius.circular(t.radius),onTap:onTap,child:Padding(padding:EdgeInsets.all(dense?12:15),child:Row(children:[Container(width:dense?40:46,height:dense?40:46,decoration:BoxDecoration(color:color.withValues(alpha:.14),borderRadius:BorderRadius.circular(dense?11:14)),child:Icon(icon,color:color)),SizedBox(width:dense?10:13),Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(title,style:Theme.of(c).textTheme.titleSmall?.copyWith(fontFamily:t.displayFont,fontWeight:t.titleWeight)),const SizedBox(height:3),Text(sub,maxLines:2,overflow:TextOverflow.ellipsis,style:Theme.of(c).textTheme.bodySmall?.copyWith(fontFamily:t.bodyFont,color:t.ink.withValues(alpha:.68),height:1.3))])),Icon(Icons.chevron_right_rounded,color:t.ink.withValues(alpha:.55),size:20)]))));
  }
  Widget _metric(BuildContext c,String label,String value,IconData icon,Color tone){final t=SkinTokens.of(c);return Expanded(child:Container(minHeight:96,padding:const EdgeInsets.all(13),decoration:BoxDecoration(color:Color.lerp(t.surface,tone,.08),borderRadius:BorderRadius.circular(t.radius),border:Border.all(color:tone.withValues(alpha:.16))),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Icon(icon,color:tone,size:20),const Spacer(),Text(value,maxLines:1,overflow:TextOverflow.ellipsis,style:Theme.of(c).textTheme.titleMedium?.copyWith(fontFamily:t.numberFont,fontWeight:FontWeight.w800)),const SizedBox(height:2),Text(label,style:Theme.of(c).textTheme.labelSmall?.copyWith(fontFamily:t.bodyFont,color:t.ink.withValues(alpha:.65)))])));}
  Widget _quick(BuildContext c,{bool grid=true}){final t=SkinTokens.of(c);final rows=quickServices.take(4).toList();if(rows.isEmpty)return const SizedBox.shrink();if(!grid)return Column(children:[for(final s in rows)Padding(padding:const EdgeInsets.only(bottom:9),child:_card(c,title:serviceLabel('${s['id']}','${s['label']}'),sub:serviceCaption('${s['id']}'),icon:serviceIcon('${s['id']}'),tone:skinServiceColour('${s['id']}'),dense:true,onTap:()=>onOpen(s)))]);return GridView.builder(shrinkWrap:true,physics:const NeverScrollableScrollPhysics(),itemCount:rows.length,gridDelegate:SliverGridDelegateWithFixedCrossAxisCount(crossAxisCount:2,crossAxisSpacing:10,mainAxisSpacing:10,mainAxisExtent:t.skin==AppSkin.friendlyModern?126:112),itemBuilder:(_,i){final s=rows[i],id='${s['id']}',tone=skinServiceColour(id);return Material(color:Color.lerp(t.surface,tone,.10),borderRadius:BorderRadius.circular(t.radius),child:InkWell(borderRadius:BorderRadius.circular(t.radius),onTap:()=>onOpen(s),child:Padding(padding:const EdgeInsets.all(12),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Icon(serviceIcon(id),color:tone,size:25),const Spacer(),Text(serviceLabel(id,'${s['label']}'),maxLines:2,overflow:TextOverflow.ellipsis,style:Theme.of(c).textTheme.titleSmall?.copyWith(fontFamily:t.displayFont,fontWeight:t.titleWeight))]))));});}
  Widget _welcome(BuildContext c,{bool showMeta=true})=>_heading(c,greeting,sub:showMeta?meta:null);
  Widget _setup(BuildContext c)=>setupNeeded?Padding(padding:const EdgeInsets.only(bottom:12),child:_card(c,title:'Complete your student profile',sub:'Add programme, level, study centre and semester.',icon:Icons.badge_outlined,onTap:onSetup)):const SizedBox.shrink();
  Widget _smart(BuildContext c)=>_baseList(c,[_welcome(c),birthday,_setup(c),Container(padding:const EdgeInsets.all(16),decoration:BoxDecoration(color:SkinTokens.of(c).surface,borderRadius:BorderRadius.circular(18)),child:Row(children:[Icon(Icons.account_balance_wallet_rounded,color:SkinTokens.of(c).primary,size:30),const SizedBox(width:12),Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text('Wallet balance',style:Theme.of(c).textTheme.labelMedium),Text(walletBalance,style:Theme.of(c).textTheme.headlineSmall?.copyWith(fontWeight:FontWeight.w800))])),FilledButton.tonal(onPressed:onWallet,child:const Text('Open'))])),const SizedBox(height:12),Row(children:[_metric(c,'Registered courses','$courseCount',Icons.menu_book_rounded,Colors.green),const SizedBox(width:10),_metric(c,'Next exam','Check timetable',Icons.calendar_month_rounded,Colors.red)]),const SizedBox(height:14),_card(c,title:'Continue studying',sub:'Open your courses and choose the next chapter.',icon:Icons.play_circle_fill_rounded,onTap:onStudy,tone:Colors.green),const SizedBox(height:18),_heading(c,'Quick tools'),_quick(c),const SizedBox(height:18),_heading(c,'Latest updates'),latestUpdates]);
  Widget _dark(BuildContext c){final t=SkinTokens.of(c);return _baseList(c,[_welcome(c),motivation,_setup(c),_card(c,title:'Next examination',sub:'Check your verified personal timetable.',icon:Icons.event_rounded,onTap:onExam,tone:t.gold,darkCard:true),const SizedBox(height:10),_card(c,title:'Continue studying',sub:courseCount==0?'Add your courses to begin.':'$courseCount courses ready in your library.',icon:Icons.auto_stories_rounded,onTap:onStudy,tone:Colors.greenAccent,darkCard:true),const SizedBox(height:12),Row(children:[_metric(c,'Wallet',walletBalance,Icons.account_balance_wallet_rounded,t.gold),const SizedBox(width:10),_metric(c,'Courses','$courseCount',Icons.school_rounded,t.primary)]),const SizedBox(height:18),_heading(c,'Quick actions'),_quick(c,grid:true),const SizedBox(height:18),_heading(c,'Latest from NOUN Update'),latestUpdates]);}
  Widget _glass(BuildContext c){final t=SkinTokens.of(c);Widget glass(Widget child)=>ClipRRect(borderRadius:BorderRadius.circular(28),child:BackdropFilter(filter:ui.ImageFilter.blur(sigmaX:12,sigmaY:12),child:Container(padding:const EdgeInsets.all(16),decoration:BoxDecoration(color:t.surface.withValues(alpha:.58),borderRadius:BorderRadius.circular(28),border:Border.all(color:Colors.white.withValues(alpha:.34))),child:child)));return _baseList(c,[_welcome(c),glass(Column(crossAxisAlignment:CrossAxisAlignment.start,children:[motivation,const SizedBox(height:10),Text('Your semester at a glance',style:Theme.of(c).textTheme.titleLarge?.copyWith(fontFamily:t.displayFont,fontWeight:t.headingWeight)),const SizedBox(height:12),Row(children:[_metric(c,'Wallet',walletBalance,Icons.wallet_rounded,t.gold),const SizedBox(width:10),_metric(c,'Courses','$courseCount',Icons.auto_stories_rounded,t.primary)])])),const SizedBox(height:14),_setup(c),glass(Column(children:[_card(c,title:'Next exam',sub:'Open your personalised timetable.',icon:Icons.calendar_month_rounded,onTap:onExam,tone:Colors.redAccent),const SizedBox(height:10),_card(c,title:'Continue studying',sub:'Pick up where you left off.',icon:Icons.play_arrow_rounded,onTap:onStudy,tone:t.primary)])),const SizedBox(height:18),_heading(c,'Shortcuts'),_quick(c),const SizedBox(height:18),_heading(c,'Updates'),latestUpdates]);}
  Widget _student(BuildContext c)=>_baseList(c,[_welcome(c),motivation,_setup(c),_card(c,title:'Important academic notice',sub:'Review the latest examination and registration updates.',icon:Icons.campaign_rounded,onTap:onExam,tone:Colors.red),const SizedBox(height:10),Row(children:[_metric(c,'Next exam','Timetable',Icons.calendar_month_rounded,Colors.green),const SizedBox(width:10),_metric(c,'My wallet',walletBalance,Icons.wallet_rounded,Colors.amber)]),const SizedBox(height:15),_card(c,title:'Continue studying',sub:courseCount==0?'Add your first course.':'Choose from $courseCount saved courses.',icon:Icons.menu_book_rounded,onTap:onStudy,tone:Colors.green),const SizedBox(height:18),_heading(c,'Quick tools'),_quick(c),const SizedBox(height:18),_heading(c,'Recent post'),latestUpdates]);
  Widget _minimal(BuildContext c){final t=SkinTokens.of(c);return _baseList(c,[_welcome(c),_setup(c),Container(padding:const EdgeInsets.symmetric(vertical:16),decoration:BoxDecoration(border:Border(top:BorderSide(color:t.ink.withValues(alpha:.10)),bottom:BorderSide(color:t.ink.withValues(alpha:.10)))),child:_card(c,title:'Next examination',sub:'No guessed dates — open your personalised timetable.',icon:Icons.calendar_today_outlined,onTap:onExam,tone:t.primary,dense:true)),const SizedBox(height:18),Row(children:[_metric(c,'Courses','$courseCount',Icons.book_outlined,t.primary),const SizedBox(width:10),_metric(c,'Wallet',walletBalance,Icons.account_balance_wallet_outlined,t.gold)]),const SizedBox(height:20),_heading(c,'Quick actions'),_quick(c),const SizedBox(height:22),_heading(c,'Updates'),latestUpdates]);}
  Widget _editorial(BuildContext c){final t=SkinTokens.of(c);return _baseList(c,[_welcome(c),Padding(padding:const EdgeInsets.only(bottom:14),child:Text('“A focused semester is built one deliberate study session at a time.”',style:Theme.of(c).textTheme.titleLarge?.copyWith(fontFamily:'NUReading',fontStyle:FontStyle.italic,height:1.35,color:t.primary))),_setup(c),_card(c,title:'Next examination',sub:'Review your personal timetable and prepare with intention.',icon:Icons.event_note_rounded,onTap:onExam,tone:Colors.red.shade700),const SizedBox(height:12),_card(c,title:'Continue studying',sub:'Return to your reading and revision library.',icon:Icons.auto_stories_rounded,onTap:onStudy,tone:t.primary),const SizedBox(height:18),Row(children:[_metric(c,'Wallet',walletBalance,Icons.wallet_outlined,t.gold),const SizedBox(width:10),_metric(c,'Courses','$courseCount',Icons.school_outlined,t.primary)]),const SizedBox(height:22),_heading(c,'Selected tools'),_quick(c),const SizedBox(height:22),_heading(c,'Latest dispatches'),latestUpdates]);}
  Widget _productivity(BuildContext c){final t=SkinTokens.of(c);return _baseList(c,[_welcome(c),_setup(c),Container(padding:const EdgeInsets.all(16),decoration:BoxDecoration(color:t.primary,borderRadius:BorderRadius.circular(12)),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text('NEXT EXAM',style:Theme.of(c).textTheme.labelSmall?.copyWith(color:Colors.white70,letterSpacing:1.2,fontFamily:t.bodyFont)),const SizedBox(height:8),Text('Open your personalised timetable',style:Theme.of(c).textTheme.titleLarge?.copyWith(color:Colors.white,fontFamily:t.displayFont,fontWeight:FontWeight.w800)),const SizedBox(height:12),FilledButton.tonal(onPressed:onExam,child:const Text('View timetable'))])),const SizedBox(height:12),Row(children:[_metric(c,'Academic tasks','$courseCount courses',Icons.checklist_rounded,Colors.red),const SizedBox(width:8),_metric(c,'Wallet',walletBalance,Icons.wallet_rounded,Colors.teal),const SizedBox(width:8),_metric(c,'Study','Resume',Icons.play_arrow_rounded,Colors.blue)]),const SizedBox(height:18),_card(c,title:'Continue studying',sub:'Move one course forward today.',icon:Icons.menu_book_rounded,onTap:onStudy,tone:t.primary),const SizedBox(height:20),_heading(c,'Command shortcuts'),_quick(c),const SizedBox(height:20),_heading(c,'Latest from NOUN Update'),latestUpdates]);}
  Widget _friendly(BuildContext c)=>_baseList(c,[_welcome(c),motivation,_setup(c),_card(c,title:'Upcoming exam',sub:'Open your timetable and see what is next.',icon:Icons.calendar_month_rounded,onTap:onExam,tone:Colors.green),const SizedBox(height:10),_card(c,title:'Latest academic notice',sub:'Stay ahead of deadlines and important changes.',icon:Icons.notifications_active_rounded,onTap:()=>onOpen({'id':'news','label':'News'}),tone:Colors.redAccent),const SizedBox(height:15),_card(c,title:'Continue studying',sub:courseCount==0?'Start by adding your courses.':'$courseCount courses are ready for you.',icon:Icons.play_circle_rounded,onTap:onStudy,tone:Colors.green),const SizedBox(height:18),_heading(c,'My quick tools'),_quick(c),const SizedBox(height:18),_heading(c,'What’s new'),latestUpdates]);
  Widget _tech(BuildContext c){final t=SkinTokens.of(c);return _baseList(c,[_welcome(c),_setup(c),Container(padding:const EdgeInsets.all(14),decoration:BoxDecoration(color:Colors.black.withValues(alpha:.24),borderRadius:BorderRadius.circular(16),border:Border.all(color:t.primary.withValues(alpha:.42)),boxShadow:[BoxShadow(color:t.primary.withValues(alpha:.10),blurRadius:18)]),child:Row(children:[for(final item in [(Icons.school_rounded,'Courses','$courseCount'),(Icons.wallet_rounded,'Wallet',walletBalance)])Expanded(child:Column(children:[Icon(item.$1,color:t.primary),const SizedBox(height:8),Text(item.$3,maxLines:1,overflow:TextOverflow.ellipsis,style:Theme.of(c).textTheme.titleMedium?.copyWith(fontFamily:t.numberFont,fontWeight:FontWeight.w800)),Text(item.$2,style:Theme.of(c).textTheme.labelSmall?.copyWith(fontFamily:t.bodyFont,letterSpacing:.8))]))])),const SizedBox(height:12),_card(c,title:'NEXT EXAM',sub:'Open secure personalised timetable data.',icon:Icons.calendar_month_rounded,onTap:onExam,tone:Colors.redAccent,darkCard:true),const SizedBox(height:10),_card(c,title:'CONTINUE STUDY',sub:'Resume your academic workspace.',icon:Icons.play_circle_outline_rounded,onTap:onStudy,tone:t.primary,darkCard:true),const SizedBox(height:18),_heading(c,'QUICK MODULES'),_quick(c),const SizedBox(height:18),_heading(c,'LIVE UPDATES'),latestUpdates]);}
  Widget _bold(BuildContext c){final t=SkinTokens.of(c);return _baseList(c,[_welcome(c),birthday,_setup(c),Container(padding:const EdgeInsets.all(17),decoration:BoxDecoration(gradient:LinearGradient(colors:[t.primary,Color.lerp(t.primary,t.gold,.34)!]),borderRadius:BorderRadius.circular(16)),child:Row(children:[const Icon(Icons.account_balance_wallet_rounded,color:Colors.white,size:30),const SizedBox(width:12),Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text('Wallet balance',style:Theme.of(c).textTheme.labelMedium?.copyWith(color:Colors.white70)),Text(walletBalance,style:Theme.of(c).textTheme.headlineSmall?.copyWith(fontFamily:t.numberFont,fontWeight:FontWeight.w900,color:Colors.white))])),FilledButton(style:FilledButton.styleFrom(backgroundColor:t.gold,foregroundColor:Colors.black87),onPressed:onWallet,child:const Text('OPEN'))])),const SizedBox(height:12),_card(c,title:'IMPORTANT UPDATE',sub:'Review current academic notices and deadlines.',icon:Icons.campaign_rounded,onTap:()=>onOpen({'id':'news','label':'News'}),tone:Colors.red),const SizedBox(height:10),Row(children:[_metric(c,'Courses','$courseCount',Icons.menu_book_rounded,t.primary),const SizedBox(width:10),_metric(c,'Next exam','Timetable',Icons.calendar_month_rounded,Colors.red)]),const SizedBox(height:18),_card(c,title:'CONTINUE STUDYING',sub:'Keep your semester moving.',icon:Icons.play_arrow_rounded,onTap:onStudy,tone:t.gold),const SizedBox(height:18),_heading(c,'ESSENTIAL TOOLS'),_quick(c),const SizedBox(height:18),_heading(c,'LATEST UPDATE'),latestUpdates]);}
}

class PremiumStudyLayout extends StatelessWidget {
  const PremiumStudyLayout({super.key,required this.courseCount,required this.services,required this.onCourses,required this.onOpen,required this.onSaved,required this.onDownloads,required this.onFocus});
  final int courseCount;final List<Map<String,dynamic>> services;final VoidCallback onCourses,onSaved,onDownloads,onFocus;final void Function(Map<String,dynamic>) onOpen;
  @override Widget build(BuildContext context){
    final t=SkinTokens.of(context),grid=[AppSkin.glassmorphism,AppSkin.studentFriendly,AppSkin.elegantEditorial,AppSkin.productivityDashboard,AppSkin.friendlyModern,AppSkin.boldPremium].contains(t.skin);
    return ListView(key:const PageStorageKey('study'),padding:const EdgeInsets.fromLTRB(18,18,18,28),children:[
      _StudyHeader(courseCount:courseCount,onCourses:onCourses),const SizedBox(height:16),
      if(t.skin==AppSkin.productivityDashboard)_overview(context),
      _SectionTitle('Study resources',subtitle:t.skin==AppSkin.futureTech?'ACADEMIC MODULES':'Everything you need to prepare with confidence.'),const SizedBox(height:10),
      grid?_grid(context):_list(context),const SizedBox(height:20),
      _SectionTitle(t.skin==AppSkin.elegantEditorial?'Your library':'Study workspace'),const SizedBox(height:10),
      Row(children:[Expanded(child:_mini(context,'Saved',Icons.bookmark_border,onSaved)),const SizedBox(width:10),Expanded(child:_mini(context,'Downloads',Icons.download_outlined,onDownloads)),const SizedBox(width:10),Expanded(child:_mini(context,'Focus',Icons.timer_outlined,onFocus))]),
    ]);
  }
  Widget _overview(BuildContext c){final t=SkinTokens.of(c);return Padding(padding:const EdgeInsets.only(bottom:18),child:Row(children:[Expanded(child:_dash(c,'Courses','$courseCount',Icons.menu_book_rounded,t.primary)),const SizedBox(width:8),Expanded(child:_dash(c,'Revision','Ready',Icons.insights_rounded,Colors.blue)),const SizedBox(width:8),Expanded(child:_dash(c,'Focus','Start',Icons.timer_rounded,Colors.orange))]));}
  Widget _dash(BuildContext c,String a,String b,IconData i,Color tone)=>Container(height:94,padding:const EdgeInsets.all(11),decoration:BoxDecoration(color:Color.lerp(SkinTokens.of(c).surface,tone,.08),borderRadius:BorderRadius.circular(12)),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Icon(i,color:tone,size:20),const Spacer(),Text(b,style:Theme.of(c).textTheme.titleSmall?.copyWith(fontWeight:FontWeight.w800)),Text(a,style:Theme.of(c).textTheme.labelSmall)]));
  Widget _list(BuildContext c)=>Column(children:[for(final s in services)Padding(padding:const EdgeInsets.only(bottom:10),child:_studyCard(c,s,false))]);
  Widget _grid(BuildContext c)=>GridView.builder(shrinkWrap:true,physics:const NeverScrollableScrollPhysics(),itemCount:services.length,gridDelegate:SliverGridDelegateWithFixedCrossAxisCount(crossAxisCount:MediaQuery.textScalerOf(c).scale(14)>18?1:2,crossAxisSpacing:10,mainAxisSpacing:10,mainAxisExtent:150),itemBuilder:(_,i)=>_studyCard(c,services[i],true));
  Widget _studyCard(BuildContext c,Map<String,dynamic> s,bool grid){final t=SkinTokens.of(c),id='${s['id']}',tone=skinServiceColour(id);final tech=t.skin==AppSkin.futureTech;final glass=t.skin==AppSkin.glassmorphism;final editorial=t.skin==AppSkin.elegantEditorial;return Material(color:tech?Colors.black.withValues(alpha:.22):Color.lerp(t.surface,tone,glass?.12:.08),borderRadius:BorderRadius.circular(t.radius),child:InkWell(borderRadius:BorderRadius.circular(t.radius),onTap:()=>onOpen(s),child:Container(padding:const EdgeInsets.all(14),decoration:BoxDecoration(borderRadius:BorderRadius.circular(t.radius),border:Border.all(color:(tech?t.primary:tone).withValues(alpha:tech?.40:.14))),child:grid?Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Icon(serviceIcon(id),color:tone,size:30),const Spacer(),Text(serviceLabel(id,'${s['label']}'),style:Theme.of(c).textTheme.titleSmall?.copyWith(fontFamily:editorial?'NUReading':t.displayFont,fontWeight:t.titleWeight)),const SizedBox(height:4),Text(serviceCaption(id),maxLines:2,overflow:TextOverflow.ellipsis,style:Theme.of(c).textTheme.bodySmall?.copyWith(fontFamily:t.bodyFont,color:t.ink.withValues(alpha:.68))) ]):Row(children:[Container(width:46,height:46,decoration:BoxDecoration(color:tone.withValues(alpha:.12),borderRadius:BorderRadius.circular(13)),child:Icon(serviceIcon(id),color:tone)),const SizedBox(width:13),Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(serviceLabel(id,'${s['label']}'),style:Theme.of(c).textTheme.titleSmall?.copyWith(fontFamily:t.displayFont,fontWeight:t.titleWeight)),const SizedBox(height:4),Text(serviceCaption(id),style:Theme.of(c).textTheme.bodySmall?.copyWith(fontFamily:t.bodyFont,color:t.ink.withValues(alpha:.68)))])),Icon(Icons.chevron_right_rounded,color:t.ink.withValues(alpha:.52))]))));}
  Widget _mini(BuildContext c,String label,IconData icon,VoidCallback tap){final t=SkinTokens.of(c);return Material(color:t.surface,borderRadius:BorderRadius.circular(t.radius),child:InkWell(borderRadius:BorderRadius.circular(t.radius),onTap:tap,child:Padding(padding:const EdgeInsets.symmetric(vertical:14,horizontal:8),child:Column(children:[Icon(icon,color:t.primary),const SizedBox(height:7),Text(label,style:Theme.of(c).textTheme.labelMedium?.copyWith(fontFamily:t.bodyFont,fontWeight:FontWeight.w700))]))));}
}
class _StudyHeader extends StatelessWidget{
  const _StudyHeader({required this.courseCount,required this.onCourses});final int courseCount;final VoidCallback onCourses;
  @override Widget build(BuildContext c){final t=SkinTokens.of(c);final photo=[AppSkin.glassmorphism,AppSkin.studentFriendly,AppSkin.friendlyModern].contains(t.skin);return Container(minHeight:photo?190:150,decoration:BoxDecoration(borderRadius:BorderRadius.circular(t.radius),gradient:LinearGradient(colors:[Color.lerp(t.primary,Colors.black,.10)!,Color.lerp(t.primary,t.gold,.25)!])),child:ClipRRect(borderRadius:BorderRadius.circular(t.radius),child:Stack(children:[if(photo)Positioned.fill(child:Opacity(opacity:.38,child:Image.asset(t.heroAsset,fit:BoxFit.cover,alignment:Alignment.centerRight))),Positioned.fill(child:DecoratedBox(decoration:BoxDecoration(gradient:LinearGradient(colors:[t.primary.withValues(alpha:.95),t.primary.withValues(alpha:.46),Colors.transparent])))),Padding(padding:const EdgeInsets.all(18),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text('STUDY',style:Theme.of(c).textTheme.labelSmall?.copyWith(fontFamily:t.bodyFont,color:Colors.white70,letterSpacing:t.labelTracking+1)),const SizedBox(height:8),Text(t.studyHeadline,style:Theme.of(c).textTheme.headlineSmall?.copyWith(fontFamily:t.displayFont,fontWeight:t.headingWeight,letterSpacing:t.headingTracking,height:t.headingHeight,color:Colors.white)),const SizedBox(height:7),Text('$courseCount registered courses · all your revision tools in one place.',style:Theme.of(c).textTheme.bodySmall?.copyWith(fontFamily:t.bodyFont,color:Colors.white.withValues(alpha:.82))),const SizedBox(height:14),FilledButton.tonal(onPressed:onCourses,child:const Text('My Courses'))]))])));}
}

class PremiumToolsLayout extends StatelessWidget {
  const PremiumToolsLayout({super.key,required this.rows,required this.pinned,required this.onSearch,required this.onOpen,required this.onTogglePin,required this.walletBalance,required this.onWallet});
  final List<Map<String,dynamic>> rows;final Set<String> pinned;final ValueChanged<String> onSearch;final void Function(Map<String,dynamic>) onOpen,onTogglePin;final String walletBalance;final VoidCallback onWallet;
  @override Widget build(BuildContext context){
    final t=SkinTokens.of(context);
    final groups=_grouped();
    return ListView(key:const PageStorageKey('tools'),padding:EdgeInsets.fromLTRB(t.skin==AppSkin.glassmorphism?20:18,18,t.skin==AppSkin.glassmorphism?20:18,30),children:[
      _toolsHeader(context),const SizedBox(height:14),_search(context),
      if(t.skin==AppSkin.boldPremium)...[const SizedBox(height:14),_walletStrip(context)],
      if(pinned.isNotEmpty)...[const SizedBox(height:20),_SectionTitle('Pinned'),const SizedBox(height:10),_renderGroup(context,rows.where((s)=>pinned.contains('${s['id']}')).toList(),forceCompact:true)],
      for(final entry in groups.entries)...[const SizedBox(height:21),_SectionTitle(entry.key),const SizedBox(height:10),_renderGroup(context,entry.value)],
      if(rows.isEmpty)Padding(padding:const EdgeInsets.only(top:30),child:Center(child:Text('No tools match your search.',style:Theme.of(context).textTheme.bodyLarge))),
    ]);
  }
  Map<String,List<Map<String,dynamic>>> _grouped(){
    final map=<String,List<Map<String,dynamic>>>{};
    for(final s in rows){if(pinned.contains('${s['id']}'))continue;final g='${s['group']??'Academic tools'}';(map[g]??=[]).add(s);}return map;
  }
  Widget _toolsHeader(BuildContext c){final t=SkinTokens.of(c);final upper=t.skin==AppSkin.futureTech||t.skin==AppSkin.boldPremium;return Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(upper?'TOOLS':'Tools',style:Theme.of(c).textTheme.headlineMedium?.copyWith(fontFamily:t.displayFont,fontWeight:t.headingWeight,letterSpacing:t.headingTracking,height:t.headingHeight)),const SizedBox(height:5),Text(t.toolsSubtitle,style:Theme.of(c).textTheme.bodyMedium?.copyWith(fontFamily:t.bodyFont,color:t.ink.withValues(alpha:.68),height:1.35))]);}
  Widget _search(BuildContext c){final t=SkinTokens.of(c),tech=t.skin==AppSkin.futureTech,glass=t.skin==AppSkin.glassmorphism;final field=TextField(onChanged:onSearch,style:TextStyle(fontFamily:t.bodyFont),decoration:InputDecoration(prefixIcon:Icon(Icons.search_rounded,color:t.primary),hintText:'Find a tool',hintStyle:TextStyle(fontFamily:t.bodyFont),filled:true,fillColor:tech?Colors.black.withValues(alpha:.24):t.surface.withValues(alpha:glass?.66:1),border:OutlineInputBorder(borderRadius:BorderRadius.circular(glass?28:t.radius),borderSide:BorderSide(color:(tech?t.primary:t.ink).withValues(alpha:tech?.36:.10))),enabledBorder:OutlineInputBorder(borderRadius:BorderRadius.circular(glass?28:t.radius),borderSide:BorderSide(color:(tech?t.primary:t.ink).withValues(alpha:tech?.36:.10)))));if(!glass)return field;return ClipRRect(borderRadius:BorderRadius.circular(28),child:BackdropFilter(filter:ui.ImageFilter.blur(sigmaX:10,sigmaY:10),child:field));}
  Widget _walletStrip(BuildContext c){final t=SkinTokens.of(c);return Material(color:t.primary,borderRadius:BorderRadius.circular(14),child:InkWell(borderRadius:BorderRadius.circular(14),onTap:onWallet,child:Padding(padding:const EdgeInsets.all(14),child:Row(children:[Container(width:44,height:44,decoration:BoxDecoration(color:t.gold,borderRadius:BorderRadius.circular(12)),child:const Icon(Icons.account_balance_wallet_rounded,color:Colors.black87)),const SizedBox(width:12),Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text('Wallet balance',style:Theme.of(c).textTheme.labelSmall?.copyWith(color:Colors.white70)),Text(walletBalance,style:Theme.of(c).textTheme.titleLarge?.copyWith(fontFamily:t.numberFont,fontWeight:FontWeight.w900,color:Colors.white))])),const Icon(Icons.chevron_right,color:Colors.white)]))));}
  Widget _renderGroup(BuildContext c,List<Map<String,dynamic>> items,{bool forceCompact=false}){
    final t=SkinTokens.of(c);
    final grid=forceCompact||[AppSkin.studentFriendly,AppSkin.elegantEditorial,AppSkin.productivityDashboard,AppSkin.friendlyModern,AppSkin.boldPremium].contains(t.skin);
    if(!grid)return Column(children:[for(final s in items)Padding(padding:const EdgeInsets.only(bottom:10),child:_listTool(c,s))]);
    return GridView.builder(shrinkWrap:true,physics:const NeverScrollableScrollPhysics(),itemCount:items.length,gridDelegate:SliverGridDelegateWithFixedCrossAxisCount(crossAxisCount:MediaQuery.textScalerOf(c).scale(14)>18?1:2,crossAxisSpacing:10,mainAxisSpacing:10,mainAxisExtent:t.skin==AppSkin.productivityDashboard?132:t.skin==AppSkin.friendlyModern?142:126),itemBuilder:(_,i)=>_gridTool(c,items[i]));
  }
  Widget _listTool(BuildContext c,Map<String,dynamic> s){final t=SkinTokens.of(c),id='${s['id']}',tone=skinServiceColour(id),glass=t.skin==AppSkin.glassmorphism,tech=t.skin==AppSkin.futureTech,dark=t.skin==AppSkin.premiumDark;final card=Material(color:tech?Colors.black.withValues(alpha:.24):dark?Color.lerp(t.surface,Colors.black,.13):t.surface.withValues(alpha:glass?.60:1),borderRadius:BorderRadius.circular(glass?30:t.radius),child:InkWell(borderRadius:BorderRadius.circular(glass?30:t.radius),onTap:()=>onOpen(s),child:Container(padding:const EdgeInsets.all(14),decoration:BoxDecoration(borderRadius:BorderRadius.circular(glass?30:t.radius),border:Border.all(color:(tech?t.primary:glass?Colors.white:tone).withValues(alpha:tech?.44:glass?.35:.13))),child:Row(children:[Container(width:48,height:48,decoration:BoxDecoration(color:tone.withValues(alpha:dark||tech?.20:.13),borderRadius:BorderRadius.circular(14)),child:Icon(serviceIcon(id),color:tech&&tone==const Color(0xff17845a)?t.primary:tone)),const SizedBox(width:13),Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(serviceLabel(id,'${s['label']}'),style:Theme.of(c).textTheme.titleSmall?.copyWith(fontFamily:t.displayFont,fontWeight:t.titleWeight)),const SizedBox(height:4),Text(serviceCaption(id),maxLines:2,overflow:TextOverflow.ellipsis,style:Theme.of(c).textTheme.bodySmall?.copyWith(fontFamily:t.bodyFont,color:t.ink.withValues(alpha:.68),height:1.3))])),_pin(c,s)]))));if(!glass)return card;return ClipRRect(borderRadius:BorderRadius.circular(30),child:BackdropFilter(filter:ui.ImageFilter.blur(sigmaX:12,sigmaY:12),child:card));}
  Widget _gridTool(BuildContext c,Map<String,dynamic> s){final t=SkinTokens.of(c),id='${s['id']}',tone=skinServiceColour(id);final productivity=t.skin==AppSkin.productivityDashboard;final friendly=t.skin==AppSkin.friendlyModern||t.skin==AppSkin.studentFriendly;final editorial=t.skin==AppSkin.elegantEditorial;final bold=t.skin==AppSkin.boldPremium;return Material(color:bold?Color.lerp(t.surface,tone,.13):Color.lerp(t.surface,tone,friendly?.08:.10),borderRadius:BorderRadius.circular(t.radius),child:InkWell(borderRadius:BorderRadius.circular(t.radius),onTap:()=>onOpen(s),child:Padding(padding:const EdgeInsets.all(13),child:Stack(children:[Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Container(width:40,height:40,decoration:BoxDecoration(color:tone.withValues(alpha:.14),borderRadius:BorderRadius.circular(productivity?10:13)),child:Icon(serviceIcon(id),color:tone,size:23)),const Spacer(),Text(serviceLabel(id,'${s['label']}'),maxLines:2,overflow:TextOverflow.ellipsis,style:Theme.of(c).textTheme.titleSmall?.copyWith(fontFamily:editorial?'NUReading':t.displayFont,fontWeight:t.titleWeight,height:1.12)),if(!productivity)...[const SizedBox(height:3),Text(serviceCaption(id),maxLines:1,overflow:TextOverflow.ellipsis,style:Theme.of(c).textTheme.bodySmall?.copyWith(fontFamily:t.bodyFont,fontSize:10,color:t.ink.withValues(alpha:.65)))] ]),Positioned(top:-8,right:-8,child:_pin(c,s,small:true))]))));}
  Widget _pin(BuildContext c,Map<String,dynamic> s,{bool small=false}){final id='${s['id']}',on=pinned.contains(id),t=SkinTokens.of(c);return IconButton(visualDensity:small?VisualDensity.compact:VisualDensity.standard,tooltip:on?'Unpin tool':'Pin tool',onPressed:()=>onTogglePin(s),icon:Icon(on?Icons.push_pin_rounded:Icons.push_pin_outlined,size:small?17:20,color:on?t.primary:t.ink.withValues(alpha:.48)));}
}

class _SectionTitle extends StatelessWidget{
  const _SectionTitle(this.title,{this.subtitle});final String title;final String? subtitle;
  @override Widget build(BuildContext c){final t=SkinTokens.of(c);return Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(title,style:Theme.of(c).textTheme.titleLarge?.copyWith(fontFamily:t.displayFont,fontWeight:t.headingWeight,letterSpacing:t.headingTracking)),if(subtitle!=null)Padding(padding:const EdgeInsets.only(top:3),child:Text(subtitle!,style:Theme.of(c).textTheme.bodySmall?.copyWith(fontFamily:t.bodyFont,color:t.ink.withValues(alpha:.62))))]);}
}
