import 'dart:async';
import 'dart:convert';
import 'package:flutter/material.dart';
import 'package:pdfx/pdfx.dart';
import 'package:shared_preferences/shared_preferences.dart';
import 'package:webview_flutter/webview_flutter.dart';
import '../core/api_client.dart';
import '../widgets/native_ui.dart';

class NativePdf extends StatefulWidget {const NativePdf({super.key,required this.api,required this.path,required this.title});final ApiClient api;final String path,title;@override State<NativePdf> createState()=>_NativePdfState();}
class _NativePdfState extends State<NativePdf>{PdfControllerPinch? controller;Object? error;@override void initState(){super.initState();load();}Future<void> load()async{try{final bytes=await widget.api.getPdf(widget.path);if(mounted)setState(()=>controller=PdfControllerPinch(document:PdfDocument.openData(bytes)));}catch(e){if(mounted)setState(()=>error=e);}}@override void dispose(){controller?.dispose();super.dispose();}@override Widget build(BuildContext context)=>NuPage(title:widget.title,child:controller!=null?PdfViewPinch(controller:controller!):error!=null?Center(child:AsyncError(error!,(){setState(()=>error=null);load();})):const Center(child:CircularProgressIndicator()));}

class NativeCheckout extends StatefulWidget {const NativeCheckout(this.url,{super.key});final String url;@override State<NativeCheckout> createState()=>_NativeCheckoutState();}
class _NativeCheckoutState extends State<NativeCheckout>{WebViewController? controller;String? error;bool returned=false;int progress=0;
 @override void initState(){super.initState();final uri=Uri.tryParse(widget.url);if(uri==null||uri.scheme!='https'||!(uri.host=='paystack.com'||uri.host.endsWith('.paystack.com'))){error='Invalid payment address.';return;}
 controller=WebViewController()..setJavaScriptMode(JavaScriptMode.unrestricted)..setNavigationDelegate(NavigationDelegate(onProgress:(v){if(mounted)setState(()=>progress=v);},onNavigationRequest:(request){final u=Uri.tryParse(request.url);if(u==null||u.scheme!='https')return NavigationDecision.prevent;if(u.host=='nounupdate.com'||u.host.endsWith('.nounupdate.com')){if(!returned){returned=true;WidgetsBinding.instance.addPostFrameCallback((_){if(mounted)Navigator.pop(context);});}return NavigationDecision.prevent;}return NavigationDecision.navigate;},onWebResourceError:(e){if(e.isForMainFrame==true&&mounted)setState(()=>error='Payment could not load. Close this screen and recheck the same payment.');}))..loadRequest(uri);
 }
 @override Widget build(BuildContext context)=>NuPage(title:'Secure Paystack payment',actions:[TextButton(onPressed:()=>Navigator.pop(context),child:const Text('Done',style:TextStyle(color:nuGold)))],child:Column(children:[if(progress<100)LinearProgressIndicator(value:progress/100),if(error!=null)Padding(padding:const EdgeInsets.all(16),child:Text(error!)),if(controller!=null)Expanded(child:WebViewWidget(controller:controller!))]));}

class MaterialLibrary extends StatefulWidget {const MaterialLibrary({super.key,required this.api,this.userId,this.summaries=false});final ApiClient api;final String? userId;final bool summaries;@override State<MaterialLibrary> createState()=>_MaterialLibraryState();}
class _MaterialLibraryState extends State<MaterialLibrary>{List<Map<String,dynamic>> rows=[];String query='';Object? error;bool busy=false,more=false;int page=1;@override void initState(){super.initState();load();}
 Future<void> load({bool next=false})async{if(busy)return;setState(()=>busy=true);try{final p=next?page+1:1;final data=unpack(await widget.api.getJson('/materials?q=${Uri.encodeQueryComponent(query)}&page=$p'));if(mounted)setState((){rows=next?[...rows,...records(data['items'])]:records(data['items']);page=p;more=data['has_more']==true;error=null;});}catch(e){if(mounted)setState(()=>error=e);}finally{if(mounted)setState(()=>busy=false);}}
 @override Widget build(BuildContext context)=>NuPage(title:widget.summaries?'Course Summary':'Study & course materials',child:Column(children:[Padding(padding:const EdgeInsets.all(16),child:TextField(onChanged:(v)=>query=v,onSubmitted:(_)=>load(),decoration:InputDecoration(hintText:'Search course code or title',prefixIcon:const Icon(Icons.search),suffixIcon:IconButton(onPressed:()=>load(),icon:const Icon(Icons.arrow_forward))))),if(busy)const LinearProgressIndicator(),if(error!=null)AsyncError(error!,()=>load()),Expanded(child:ListView(padding:const EdgeInsets.symmetric(horizontal:16),children:[for(final row in rows)NuPanel(padding:0,child:ListTile(contentPadding:const EdgeInsets.all(12),leading:GlossIcon(Icons.menu_book_rounded,size:46,color:serviceColour(widget.summaries?'course-summary':'courses')),title:Text('${row['course_code']}',style:const TextStyle(fontWeight:FontWeight.w800)),subtitle:Text('${row['title']??row['course_code']}'),trailing:const Icon(Icons.chevron_right),onTap:()=>pushNu(context,widget.summaries?NativeSummary(api:widget.api,code:'${row['course_code']}',signedIn:widget.userId!=null):NativeStudy(api:widget.api,row:row,userId:widget.userId)))),if(more)TextButton(onPressed:()=>load(next:true),child:const Text('Load more')),if(!busy&&error==null&&rows.isEmpty)const Padding(padding:EdgeInsets.all(24),child:Text('No materials match your search.'))]))]));}

class NativeStudy extends StatefulWidget {const NativeStudy({super.key,required this.api,required this.row,this.userId});final ApiClient api;final Map<String,dynamic> row;final String? userId;@override State<NativeStudy> createState()=>_NativeStudyState();}
class _NativeStudyState extends State<NativeStudy>{List<Map<String,dynamic>> sections=[];Set<int> done={};Object? error;bool loading=true,stateReady=false;String tab='Overview';final notes=TextEditingController();String get code=>'${widget.row['course_code']}'.replaceAll(' ','').toUpperCase();String get slot=>'nu-study-${widget.userId??'guest'}-$code';@override void initState(){super.initState();load();} @override void dispose(){notes.dispose();super.dispose();}
 Future<void> load()async{setState(()=>loading=true);try{final data=unpack(await widget.api.getJson('/study/$code'));final prefs=await SharedPreferences.getInstance();final state=widget.userId==null?jsonDecode(prefs.getString(slot)??'{}') as Map:unpack(await widget.api.getJson('/study/$code/state'));if(mounted)setState((){sections=records(data['sections']);done=(state['done'] as List? ?? []).map((x)=>(x as num).toInt()).toSet();notes.text='${state['notes']??''}';stateReady=true;error=null;});}catch(e){if(mounted)setState(()=>error=e);}finally{if(mounted)setState(()=>loading=false);}}
 Future<void> save()async{if(!stateReady)return;try{final data={'done':done.toList(),'notes':notes.text};if(widget.userId==null){await (await SharedPreferences.getInstance()).setString(slot,jsonEncode(data));}else{await widget.api.postJson('/study/$code/state',data);}if(mounted)nuMessage(context,'Study progress saved.');}catch(e){if(mounted)nuMessage(context,e);}}
 @override Widget build(BuildContext context){final percent=sections.isEmpty?0.0:done.where((i)=>i<sections.length).length/sections.length;return NuPage(title:'Study',child:ListView(padding:const EdgeInsets.all(16),children:[NuPanel(child:Row(children:[const GlossIcon(Icons.work_rounded),const SizedBox(width:14),Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[const Text('YOUR COURSE',style:TextStyle(fontSize:10,color:nuGreen)),Text('$code · ${widget.row['title']??''}',style:const TextStyle(fontSize:18,fontWeight:FontWeight.w800))])),SizedBox(width:54,height:54,child:Stack(alignment:Alignment.center,children:[CircularProgressIndicator(value:percent,backgroundColor:nuMint,strokeWidth:6),Text('${(percent*100).round()}%',style:const TextStyle(fontWeight:FontWeight.w800))]))])),
 SingleChildScrollView(scrollDirection:Axis.horizontal,child:Row(children:[for(final t in ['Overview','Modules','Reader','Quiz','Notes'])Padding(padding:const EdgeInsets.only(right:6),child:ChoiceChip(label:Text(t),selected:tab==t,onSelected:(_)=>setState(()=>tab=t)))])),const SizedBox(height:14),
 if(tab=='Notes')... [const NuTitle('My notes & review',subtitle:'Keep your own explanations, highlights and revision questions.'),TextField(controller:notes,maxLines:14,enabled:stateReady,decoration:const InputDecoration(hintText:'What did you learn today?')),FilledButton(onPressed:stateReady?save:null,child:const Text('Save notes'))]
 else if(tab=='Quiz')...[const NuTitle('Active recall'),const Text('Practise recalling a course unit, then reveal the material to check your understanding.'),FilledButton(onPressed:sections.isEmpty?null:()=>pushNu(context,StudyRecall(sections)),child:const Text('Start recall practice'))]
 else if(tab=='Reader')... [const NuTitle('Course material'),FilledButton.icon(onPressed:()=>pushNu(context,NativePdf(api:widget.api,path:'/materials/${widget.row['id']}/pdf',title:code)),icon:const Icon(Icons.menu_book),label:const Text('Open PDF reader'))]
 else ...[const NuPanel(color:nuMint,child:Row(children:[Expanded(child:Text('Build your knowledge, one unit at a time.',style:TextStyle(fontWeight:FontWeight.w700,color:nuDeep))),GlossIcon(Icons.school_rounded,color:nuGreen,size:48)])),const NuTitle('Course modules'),if(loading)const LinearProgressIndicator(),if(error!=null)AsyncError(error!,load),for(var i=0;i<sections.length;i++)NuPanel(padding:4,child:ListTile(leading:GlossIcon(Icons.menu_book_rounded,label:'${i+1}',size:40,color:i%3==1?nuGold:i%3==2?nuRed:nuGreen),title:Text('${sections[i]['unit_title']}',style:const TextStyle(fontSize:14,fontWeight:FontWeight.w700)),subtitle:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text('${sections[i]['module_title']}',style:const TextStyle(fontSize:11)),const SizedBox(height:6),LinearProgressIndicator(value:done.contains(i)?1:0,backgroundColor:nuMint)]),trailing:Icon(done.contains(i)?Icons.check_circle:Icons.chevron_right,color:nuGreen),onTap:()async{final complete=await pushNu<bool>(context,NuPage(title:'${sections[i]['unit_title']}',child:ListView(padding:const EdgeInsets.all(22),children:[SelectableText('${sections[i]['source_text']}',style:const TextStyle(fontSize:16,height:1.7)),const SizedBox(height:24),FilledButton(onPressed:()=>Navigator.pop(context,true),child:const Text('Mark as read'))])));if(complete==true&&mounted){setState(()=>done.add(i));await save();}}))],
 const NuTitle('Study tools'),Row(crossAxisAlignment:CrossAxisAlignment.start,children:[
 for(final t in [('Summarize',Icons.summarize_rounded,nuGreen),('Explain',Icons.chat_bubble_rounded,nuRed),('Active Recall',Icons.psychology_rounded,nuGold),('Pomodoro',Icons.timer_rounded,nuGreen),('Voice Reader',Icons.volume_up_rounded,nuRed)])Expanded(child:InkWell(onTap:()=>pushNu(context,switch(t.$1){'Summarize'=>NativeSummary(api:widget.api,code:code,signedIn:widget.userId!=null),'Pomodoro'=>const FocusTimer(),'Active Recall'=>StudyRecall(sections),_=>NativeUnavailable(t.$1)}),child:Column(children:[GlossIcon(t.$2,color:t.$3,size:40),const SizedBox(height:7),Text(t.$1,textAlign:TextAlign.center,style:const TextStyle(fontSize:9,fontWeight:FontWeight.w700))])))]),
 const SizedBox(height:18),Row(crossAxisAlignment:CrossAxisAlignment.start,children:[Expanded(child:NuPanel(color:const Color(0xfffff0b7),padding:12,child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[const Text('Course Summary',style:TextStyle(fontSize:12,fontWeight:FontWeight.w800)),const SizedBox(height:6),const Text('A focused summary for your revision.',style:TextStyle(fontSize:10)),TextButton(onPressed:()=>pushNu(context,NativeSummary(api:widget.api,code:code,signedIn:widget.userId!=null)),child:const Text('Open summary',style:TextStyle(fontSize:10)))]))),const SizedBox(width:10),Expanded(child:NuPanel(color:nuMint,padding:12,child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[const Text('My Notes & Review',style:TextStyle(fontSize:12,fontWeight:FontWeight.w800)),const SizedBox(height:6),const Text('Keep your notes and revision questions.',style:TextStyle(fontSize:10)),TextButton(onPressed:()=>setState(()=>tab='Notes'),child:const Text('Open notebook',style:TextStyle(fontSize:10)))])))]),const SizedBox(height:20)]));}}

class NativeSummary extends StatefulWidget {const NativeSummary({super.key,required this.api,required this.code,required this.signedIn});final ApiClient api;final String code;final bool signedIn;@override State<NativeSummary> createState()=>_NativeSummaryState();}
class _NativeSummaryState extends State<NativeSummary>{Map<String,dynamic>? outline;Map<int,dynamic> generated={};Object? error;bool busy=false;
 Future<void> start()async{if(!widget.signedIn){nuMessage(context,'Sign in from Profile to use your Course Summary wallet.');return;}if(busy)return;setState(()=>busy=true);try{final access=unpack(await widget.api.getJson('/course-summary?action=check_access&course=${widget.code}'));if(!mounted)return;final yes=await showDialog<bool>(context:context,builder:(c)=>AlertDialog(title:const Text('Course Summary'),content:Text(access['has_access']==true?'Open your unlocked course?':'Unlock this course for ${naira((access['price'] as num)*100)} from your central wallet?'),actions:[TextButton(onPressed:()=>Navigator.pop(c,false),child:const Text('Cancel')),FilledButton(onPressed:()=>Navigator.pop(c,true),child:const Text('Continue'))]));if(yes!=true)return;final result=unpack(await widget.api.postJson('/course-summary?action=summarize_init',{'course_code':widget.code,'expected_price':access['price']}));if(mounted)setState(()=>outline=result);}catch(e){if(mounted)setState(()=>error=e);}finally{if(mounted)setState(()=>busy=false);}}
 Future<void> section(int i)async{if(busy)return;setState(()=>busy=true);try{final result=unpack(await widget.api.postJson('/course-summary?action=summarize_section',{'course_code':widget.code,'section_index':i}));if(mounted){setState(()=>generated[i]=result['section']);await pushNu(context,NuPage(title:'${widget.code} summary',child:ListView(padding:const EdgeInsets.all(20),children:structured(result['section']))));}}catch(e){if(mounted)setState(()=>error=e);}finally{if(mounted)setState(()=>busy=false);}}
 List<Widget> structured(dynamic x){if(x is Map)return [for(final e in x.entries)...[NuTitle('${e.key}'.replaceAll('_',' ')),...structured(e.value)]];if(x is List)return [for(final v in x)...structured(v)];return [Padding(padding:const EdgeInsets.only(bottom:10),child:SelectableText('$x',style:const TextStyle(height:1.6)))];}
 @override Widget build(BuildContext context)=>NuPage(title:'Course Summary · ${widget.code}',child:ListView(padding:const EdgeInsets.all(18),children:[const GreenBanner(title:'Revise with purpose.',text:'Your course, organised into focused study sections.',icon:Icons.summarize_rounded),const SizedBox(height:20),if(busy)const LinearProgressIndicator(),if(error!=null)AsyncError(error!,()=>setState(()=>error=null)),if(outline==null)FilledButton(onPressed:busy?null:start,child:const Text('Open course summary')),if(outline!=null)...[const NuTitle('Your summary sections',subtitle:'Generate sections in order. Previously generated content is reused.'),for(final s in records(outline!['sections']))NuPanel(child:ListTile(title:Text('${s['unit_title']}'),subtitle:Text('${s['module_title']}'),trailing:const Icon(Icons.chevron_right),onTap:busy?null:()=>section((s['index'] as num).toInt())))]]));}

class NativeFees extends StatefulWidget{const NativeFees(this.api,{super.key});final ApiClient api;@override State<NativeFees> createState()=>_NativeFeesState();}
class _NativeFeesState extends State<NativeFees>{List<Map<String,dynamic>> options=[];String? program,level,semester;Map<String,dynamic>? result;Object? error;bool busy=false;@override void initState(){super.initState();load();}Future<void> load()async{try{final d=unpack(await widget.api.getJson('/fees/options'));if(mounted)setState(()=>options=records(d['items']));}catch(e){if(mounted)setState(()=>error=e);}}
 Future<void> calculate()async{if(program==null||level==null||semester==null)return;setState(()=>busy=true);try{final r=unpack(await widget.api.postJson('/fees/calculate',{'program':program,'level':level,'semester':semester}));if(mounted)setState((){result=r;error=null;});}catch(e){if(mounted)setState(()=>error=e);}finally{if(mounted)setState(()=>busy=false);}}
 Widget select(String name,String? value,List<String> values,void Function(String?) changed)=>Padding(padding:const EdgeInsets.only(bottom:12),child:DropdownButtonFormField<String>(initialValue:value,isExpanded:true,decoration:InputDecoration(labelText:name),items:values.toSet().map((v)=>DropdownMenuItem(value:v,child:Text(v,overflow:TextOverflow.ellipsis))).toList(),onChanged:changed));
 @override Widget build(BuildContext context)=>NuPage(title:'Fee Checker',child:ListView(padding:const EdgeInsets.all(18),children:[const NuTitle('Plan your registration',subtitle:'Course and fee records from NOUN Update.'),select('Programme',program,options.map((x)=>'${x['program']}').toList(),(v)=>setState((){program=v;level=null;semester=null;result=null;})),KeyedSubtree(key:ValueKey(program),child:select('Level',level,options.where((x)=>x['program']==program).map((x)=>'${x['level']}').toList(),(v)=>setState((){level=v;semester=null;result=null;}))),KeyedSubtree(key:ValueKey('$program-$level'),child:select('Semester',semester,options.where((x)=>x['program']==program&&'${x['level']}'==level).map((x)=>'${x['semester']}').toList(),(v)=>setState(()=>semester=v))),FilledButton(onPressed:busy?null:calculate,child:const Text('Check fees')),if(busy)const LinearProgressIndicator(),if(error!=null)AsyncError(error!,load),if(result!=null)...[const NuTitle('Fee summary'),NuPanel(color:nuMint,child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[const Text('DATABASE-LISTED TOTAL'),Text(result!['total_kobo']==null?'Semester fee needs confirmation':naira(result!['total_kobo']),style:const TextStyle(fontSize:28,fontWeight:FontWeight.w800,color:nuGreen)),Text('Course fees ${naira(result!['course_kobo'])} · Exam fees ${naira(result!['exam_kobo'])}'),Text('${result!['units']} units'),const SizedBox(height:10),Text('${result!['notice']}',style:const TextStyle(fontSize:12))])),for(final r in records(result!['items']))NuPanel(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text('${r['code']} · ${r['title']}',style:const TextStyle(fontWeight:FontWeight.w700)),Text('${r['units']} units · ${r['status']}'),Text('Course ${naira(r['course_kobo'])} · Exam ${naira(r['exam_kobo'])}'),if(r['examinable']==false)const Text('Not examinable',style:TextStyle(color:nuGreen))]))]]));}

class NativeCalendar extends StatefulWidget{const NativeCalendar(this.api,{super.key});final ApiClient api;@override State<NativeCalendar> createState()=>_NativeCalendarState();}
class _NativeCalendarState extends State<NativeCalendar>{late Future<Map<String,dynamic>> data;String query='';@override void initState(){super.initState();reload();}void reload(){data=widget.api.getJson('/calendar').then(unpack);}@override Widget build(BuildContext context)=>NuPage(title:'Academic Calendar',child:ListView(padding:const EdgeInsets.all(18),children:[const GreenBanner(title:'Stay one step ahead.',text:'Academic dates, registration, TMAs and examinations.',icon:Icons.calendar_month_rounded),const SizedBox(height:16),TextField(onChanged:(v)=>setState(()=>query=v),decoration:const InputDecoration(prefixIcon:Icon(Icons.search),hintText:'Search dates and events')),FutureBuilder<Map<String,dynamic>>(future:data,builder:(c,s){if(s.hasError)return AsyncError(s.error!,()=>setState(reload));if(!s.hasData)return const Padding(padding:EdgeInsets.all(30),child:Center(child:CircularProgressIndicator()));final events=records(s.data!['events']).where((e)=>'${e['title']} ${e['category']}'.toLowerCase().contains(query.toLowerCase())).toList();return Column(children:[const NuTitle('Your academic dates'),for(final e in events)NuPanel(child:ListTile(contentPadding:EdgeInsets.zero,leading:const GlossIcon(Icons.calendar_month,size:46),title:Text('${e['title']}',style:const TextStyle(fontWeight:FontWeight.w700)),subtitle:Text('${e['start_at']??'Date to be confirmed'}\n${e['end_at']??''}'),onTap:()=>pushNu(context,NuPage(title:'Academic date',child:ListView(padding:const EdgeInsets.all(24),children:[NuTitle('${e['title']}'),Text('${e['start_at']??''}'),const SizedBox(height:16),SelectableText('${e['description']??e['notes']??''}')]))))),if(events.isEmpty)const Padding(padding:EdgeInsets.all(25),child:Text('No dates match this search.'))]);})]));}

class FocusTimer extends StatefulWidget{const FocusTimer({super.key});@override State<FocusTimer> createState()=>_FocusTimerState();}
class _FocusTimerState extends State<FocusTimer>{int seconds=1500;Timer? timer;@override void dispose(){timer?.cancel();super.dispose();}void toggle(){if(timer?.isActive==true){timer?.cancel();setState((){});return;}timer=Timer.periodic(const Duration(seconds:1),(t){if(seconds==0){t.cancel();}else{setState(()=>seconds--);}});setState((){});}@override Widget build(BuildContext context)=>NuPage(title:'Pomodoro focus',child:Center(child:Padding(padding:const EdgeInsets.all(30),child:Column(mainAxisSize:MainAxisSize.min,children:[const GlossIcon(Icons.timer_rounded,size:100),const NuTitle('One focused session'),Text('${seconds~/60}:${(seconds%60).toString().padLeft(2,'0')}',style:const TextStyle(fontSize:62,fontWeight:FontWeight.w800,color:nuGreen)),FilledButton(onPressed:toggle,child:Text(timer?.isActive==true?'Pause':'Start')),TextButton(onPressed:(){timer?.cancel();setState(()=>seconds=1500);},child:const Text('Reset 25 minutes'))]))));}

class NativeCgpa extends StatefulWidget{const NativeCgpa({super.key});@override State<NativeCgpa> createState()=>_NativeCgpaState();}
class _NativeCgpaState extends State<NativeCgpa>{final units=TextEditingController();List<(int,int)> rows=[];int grade=5;@override void dispose(){units.dispose();super.dispose();}@override Widget build(BuildContext context){final total=rows.fold<int>(0,(v,r)=>v+r.$1),points=rows.fold<int>(0,(v,r)=>v+r.$1*r.$2);return NuPage(title:'CGPA Calculator',child:ListView(padding:const EdgeInsets.all(20),children:[GreenBanner(title:total==0?'Your CGPA':'${(points/total).toStringAsFixed(2)} / 5.00',text:'Manual estimate · $total course units',icon:Icons.calculate),const NuTitle('Add a course'),TextField(controller:units,keyboardType:TextInputType.number,decoration:const InputDecoration(labelText:'Course units')),DropdownButton<int>(value:grade,items:[for(var i=5;i>=0;i--)DropdownMenuItem(value:i,child:Text('${['F','E','D','C','B','A'][i]} · $i points'))],onChanged:(v)=>setState(()=>grade=v!)),FilledButton(onPressed:(){final n=int.tryParse(units.text);if(n==null||n<1||n>30){nuMessage(context,'Enter valid course units.');return;}setState(()=>rows.add((n,grade)));units.clear();},child:const Text('Add course')),for(var i=0;i<rows.length;i++)ListTile(title:Text('Course ${i+1} · ${rows[i].$1} units'),subtitle:Text('${rows[i].$2} grade points'),trailing:IconButton(icon:const Icon(Icons.close),onPressed:()=>setState(()=>rows.removeAt(i)))),const Text('This is a manual estimate. Your institution’s official result remains authoritative.') ]));}}

class AcademicOverview extends StatefulWidget {
 const AcademicOverview({super.key,required this.api});final ApiClient api;
 @override State<AcademicOverview> createState()=>_AcademicOverviewState();
}
class _AcademicOverviewState extends State<AcademicOverview>{
 late Future<Map<String,dynamic>> calendar;
 @override void initState(){super.initState();calendar=widget.api.getJson('/calendar').then(unpack);}
 @override Widget build(BuildContext context)=>FutureBuilder<Map<String,dynamic>>(future:calendar,builder:(c,s){
  final events=records(s.data?['events']);
  final upcoming=events.where((e){final date=DateTime.tryParse('${e['start_at']}');return date!=null&&date.isAfter(DateTime.now());}).toList()..sort((a,b)=>'${a['start_at']}'.compareTo('${b['start_at']}'));
  final next=upcoming.isEmpty?null:upcoming.first;
  final known=s.hasData&&s.data!['events'] is List;
  String count(String term)=>known?'${upcoming.where((e)=>'${e['category']} ${e['title']}'.toLowerCase().contains(term)).length}':'—';
  return Column(children:[Row(crossAxisAlignment:CrossAxisAlignment.start,children:[
   for(final r in [('TMA',count('tma'),Icons.assignment_rounded,nuGreen),('Exams',count('exam'),Icons.school_rounded,nuRed),('Fees','Check',Icons.account_balance_wallet_rounded,nuGold),('Calendar',known?'${upcoming.length}':'—',Icons.calendar_month_rounded,nuGreen)])
    Expanded(child:Padding(padding:const EdgeInsets.symmetric(horizontal:3),child:Material(color:Color.lerp(Colors.white,r.$4,.07),borderRadius:BorderRadius.circular(13),child:InkWell(borderRadius:BorderRadius.circular(13),onTap:()=>pushNu(context,r.$1=='Fees'?NativeFees(widget.api):NativeCalendar(widget.api)),child:Padding(padding:const EdgeInsets.symmetric(vertical:12,horizontal:5),child:Column(children:[GlossIcon(r.$3,color:r.$4,size:29),const SizedBox(height:8),Text(r.$1,style:const TextStyle(fontSize:10,fontWeight:FontWeight.w700)),Text(r.$2,style:const TextStyle(fontSize:17,fontWeight:FontWeight.w800,color:nuDeep))])))))),
  ]),const SizedBox(height:16),PhotoBanner(title:next==null?'Your semester.\nOne step ahead.':'${next['title']}',text:next==null?'Plan your studies, registration and revision.':'${DateTime.parse('${next['start_at']}').difference(DateTime.now()).inDays} days to go',onTap:()=>pushNu(context,NativeCalendar(widget.api)))]);
 });
}

class StudyRecall extends StatefulWidget {
 const StudyRecall(this.sections,{super.key});final List<Map<String,dynamic>> sections;
 @override State<StudyRecall> createState()=>_StudyRecallState();
}
class _StudyRecallState extends State<StudyRecall>{int index=0;bool revealed=false;
 @override Widget build(BuildContext context)=>NuPage(title:'Active recall',child:widget.sections.isEmpty?const Center(child:Text('Open a course with available material first.')):ListView(padding:const EdgeInsets.all(20),children:[const GlossIcon(Icons.psychology_rounded,color:nuGold,size:70),NuTitle('${widget.sections[index]['unit_title']}',subtitle:'Without looking, explain the key ideas in your own words.'),const Text('This is self-study practice. It is not an assessed quiz.'),const SizedBox(height:20),if(revealed)NuPanel(child:SelectableText('${widget.sections[index]['source_text']}',style:const TextStyle(height:1.6)))else FilledButton(onPressed:()=>setState(()=>revealed=true),child:const Text('Reveal course material')),TextButton(onPressed:()=>setState((){index=(index+1)%widget.sections.length;revealed=false;}),child:const Text('Next unit'))]));
}
